### ISSUE TITLE
Uncaught TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by jason-krypton** [highcharts/highcharts#10160]
#### Expected behaviour
Do not throw an unhandled exception.

#### Actual behaviour
Throws unhandled exception.

#### Live demo with steps to reproduce
Note: https://jsfiddle.net/gr3h9751/9/

You will need to look in the console of the JSFiddle for the unhandled error. 

```
VM99 highcharts.js:320 Uncaught TypeError: Cannot read property '0' of null
    at p.translate (VM99 highcharts.js:320)
    at p.translate (VM99 highcharts.js:375)
    at VM99 highcharts.js:281
    at Array.forEach (<anonymous>)
    at a.Chart.renderSeries (VM99 highcharts.js:281)
    at a.Chart.render (VM99 highcharts.js:283)
    at a.Chart.firstRender (VM99 highcharts.js:286)
    at a.Chart.<anonymous> (VM99 highcharts.js:260)
    at a.fireEvent (VM99 highcharts.js:31)
    at a.Chart.init (VM99 highcharts.js:259)
```

I debugged the minified JS a bit and it looks like the issue around getting stack indicators for the index 13 series.

Some code uses the key of `13,39,0` to access the points object from a `StackItem` and then access the 0th index of null, which blows up
```
points: {
  13: (2) [0, 50]
  13,39,0: null
  13,39,1: null
  13,39,2: null
  13,39,3: (2) [0, 50]
}
```

I looked closely and noticed that the index 13th series is a bit unique in every data point has the same name, but the first 3 of 4 are null. The name also appears multiple times in the category data at different locations. If I change the config to move the non null point first there is no error. There is also no error if I filter out the null points.

I'm mostly curious why this is failing, and how we should be sanitizing our data to prevent this from causing crashes.

Full config sorry about the readability I had to try and anonymize the data.
```
Highcharts.chart('container', { colors:
   [ '#7F9FDA',
     '#F6BD57',
     '#73C886',
     '#D56767',
     '#EA9562',
     '#A170B8',
     '#DB67AC',
     '#4E71B5',
     '#DA8E06',
     '#3E8A61',
     '#AE1616',
     '#C8631A',
     '#744485',
     '#BB2B81' ],
  time: { timezone: 'America/Los_Angeles' },
  xAxis:
   { allowDecimals: true,
     categories:
      [ 'c-16PXWwRnX3',
        'c-fdM64DXfTy',
        'c-EqBwcgw43A',
        'c-xJiVQHweDG',
        'c-yQzUbrI7iS',
        'c-IQiI9rpd47',
        'c-cJucG2hP0G',
        'c-eWlHvq7Dyt',
        'c-PXliQA6m0c',
        'c-yhE5TWWRt-',
        'c-ZZrRBjZQ-e',
        'c-f5kE-twxMt',
        'c-hS1M1DUojg',
        'c-uE8xKK_bVK',
        'c-VW6X3GW2ub',
        'c-l4A9mlzHbk',
        'c-ldjTuzYyLk',
        'c-QgImvOKMDQ',
        'c-Jb8uD7TKHd',
        'c-3vHrOpTy0u',
        'c-xmGL6JBMLS',
        'c-xHqrROuF91',
        'c-xHqrROuF91',
        'c-xHqrROuF91',
        'c-on7iyITyzX',
        'c-7uAAb8tn2F',
        'c-7bOJBSJ2H8',
        'c-YsJ5H-CJ9r',
        'c-rdT0_F0bpH',
        'c-_3R4oyiSRg',
        'c-xXx2qmI47S',
        'c-6uXSrqe-aw',
        'c--nXgbpdRPt',
        'c--H-_DObCDC',
        'c-lSZFyN9K4-',
        'c-qdmTDUp1i5',
        'c-dDhxTki8iv',
        'c-5FoWon2e8-',
        'c-UAhTCfxWdg',
        'c-IiZDunqozI',
        'c-PXa-fk6aPe',
        'c-IiZDunqozI',
        'c-H6YVhAeXcV',
        'c-xFQSqcpaPL',
        'c-mhNuDhedQZ',
        'c-dGbOYxsuSR',
        'c-g_mLqJMMC9',
        'c-g_mLqJMMC9',
        'c-3-B_3G2TFk',
        'c-jtafFLci2L',
        'c-Pou8aqID6H',
        'c-f0KyjkraBZ',
        'c-i1tFMWdUws',
        'c-yhb9n_ArTN',
        'c-K8lTm4ta_9',
        'c-QslUKiO3De',
        'c-eseuXgJ3yu',
        'c-w5UvAvlzy2',
        'c-8SKnFa5xfc',
        'c-nNMFH1WJLj',
        'c-vWICAsS1Qa',
        'c-3UOc_xkPXA',
        'c-3_5IsbX7Dw',
        'c-bGkegIM35g',
        'c-_3TmqaiAzj',
        'c-rqupy7OVi9',
        'c-gunaJ9Sxzt',
        'c-OhD-_zEJ0d',
        'c-WgTxqmDGW6',
        'c-Im6jQmJZqA',
        'c-Im6jQmJZqA',
        'c-OTFVqhUj8U',
        'c-IiZDunqozI',
        'c-xifIrXpHtU',
        'c-IiZDunqozI',
        'c-Rzd2bJX42Y',
        'c-ihOqTunUxu',
        'c-SGqiQqI5qG',
        'c-4U9mQDuAYS',
        'c-ATu4MMN_7h',
        'c-UISl-4Y8W_',
        'c-D37zAtneVp' ],
     labels:
      { style:
         { color: '#8e8e8e',
           fontSize: '13px',
           fontWeight: 600,
           lineHeight: '18px',
           textTransform: 'uppercase',
           fontFamily:
            '\'Source Sans Pro\', \'Source Sans\', \'Open Sans\', \'Calibri\', \'BlinkMacSystemFont\', \'Helvetica Neue\', sans-serif' } },
     max: null,
     min: null,
     title:
      { text: 'Person',
        style:
         { color: '#8e8e8e',
           fontSize: '13px',
           fontWeight: 600,
           lineHeight: '18px',
           textTransform: 'uppercase',
           fontFamily:
            '\'Source Sans Pro\', \'Source Sans\', \'Open Sans\', \'Calibri\', \'BlinkMacSystemFont\', \'Helvetica Neue\', sans-serif' } },
     type: 'category',
     lineColor: '#e0e0e0',
     tickColor: '#e0e0e0' },
  yAxis:
   { allowDecimals: false,
     endOnTick: true,
     startOnTick: true,
     max: null,
     min: null,
     title:
      { text: '% Involvement',
        style:
         { color: '#8e8e8e',
           fontSize: '13px',
           fontWeight: 600,
           lineHeight: '18px',
           textTransform: 'uppercase',
           fontFamily:
            '\'Source Sans Pro\', \'Source Sans\', \'Open Sans\', \'Calibri\', \'BlinkMacSystemFont\', \'Helvetica Neue\', sans-serif' } },
     gridLineColor: '#e0e0e0',
     labels:
      { style:
         { color: '#8e8e8e',
           fontSize: '13px',
           fontWeight: 600,
           lineHeight: '18px',
           textTransform: 'uppercase',
           fontFamily:
            '\'Source Sans Pro\', \'Source Sans\', \'Open Sans\', \'Calibri\', \'BlinkMacSystemFont\', \'Helvetica Neue\', sans-serif' } },
     reversedStacks: false },
  series:
   [ { name: 'c-w5Ngwpao0h',
       data:
        [ { name: 'c-16PXWwRnX3',
            xId: 'grid-O3kuxDa3J3/i-GnaCnMMqgg',
            y: 20,
            yDisplayValue: '20' },
          { name: 'c-yQzUbrI7iS',
            xId: 'grid-O3kuxDa3J3/i-hBQzbGYqkP',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-uE8xKK_bVK',
            xId: 'grid-O3kuxDa3J3/i-dU4kNNVy9_',
            y: null,
            yDisplayValue: '' },
          { name: 'c-7uAAb8tn2F',
            xId: 'grid-O3kuxDa3J3/i-uEZkkTT8U3',
            y: null,
            yDisplayValue: '' },
          { name: 'c-_3R4oyiSRg',
            xId: 'grid-O3kuxDa3J3/i-FacRb36_w9',
            y: null,
            yDisplayValue: '' },
          { name: 'c-6uXSrqe-aw',
            xId: 'grid-O3kuxDa3J3/i-YpD2Ep3mZM',
            y: null,
            yDisplayValue: '' },
          { name: 'c-K8lTm4ta_9',
            xId: 'grid-O3kuxDa3J3/i-mcRWCUEgVD',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-18tU8jwoOS',
       data:
        [ { name: 'c-16PXWwRnX3',
            xId: 'grid-O3kuxDa3J3/i-GnaCnMMqgg',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-WgTxqmDGW6',
            xId: 'grid-O3kuxDa3J3/i-HTxwSQCTy3',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-n-sn9fzIc4',
       data:
        [ { name: 'c-16PXWwRnX3',
            xId: 'grid-O3kuxDa3J3/i-GnaCnMMqgg',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-QgImvOKMDQ',
            xId: 'grid-O3kuxDa3J3/i-Ou_5kvtRYH',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xmGL6JBMLS',
            xId: 'grid-O3kuxDa3J3/i-O0EjEtRUg1',
            y: null,
            yDisplayValue: '' },
          { name: 'c--H-_DObCDC',
            xId: 'grid-O3kuxDa3J3/i-r3BZAZlexj',
            y: null,
            yDisplayValue: '' },
          { name: 'c-lSZFyN9K4-',
            xId: 'grid-O3kuxDa3J3/i-vEeQAwz15Y',
            y: null,
            yDisplayValue: '' },
          { name: 'c-vWICAsS1Qa',
            xId: 'grid-O3kuxDa3J3/i-0PdmWEU71c',
            y: null,
            yDisplayValue: '' },
          { name: 'c-_3TmqaiAzj',
            xId: 'grid-O3kuxDa3J3/i-e0dpq-EClg',
            y: null,
            yDisplayValue: '' },
          { name: 'c-gunaJ9Sxzt',
            xId: 'grid-O3kuxDa3J3/i-KzF__TZBqI',
            y: null,
            yDisplayValue: '' },
          { name: 'c-OTFVqhUj8U',
            xId: 'grid-O3kuxDa3J3/i-QVkXVxrZ3M',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xifIrXpHtU',
            xId: 'grid-O3kuxDa3J3/i-9eaFJC6sFz',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-xEqeMbyeqE',
       data:
        [ { name: 'c-fdM64DXfTy',
            xId: 'grid-O3kuxDa3J3/i-MBIAt5899k',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-IQiI9rpd47',
            xId: 'grid-O3kuxDa3J3/i-b4cIbpGMc9',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-ZZrRBjZQ-e',
            xId: 'grid-O3kuxDa3J3/i-MYVzFkksRm',
            y: null,
            yDisplayValue: '' },
          { name: 'c-f5kE-twxMt',
            xId: 'grid-O3kuxDa3J3/i-u_uhqag3-6',
            y: null,
            yDisplayValue: '' },
          { name: 'c-5FoWon2e8-',
            xId: 'grid-O3kuxDa3J3/i-Xbx8JxH1uZ',
            y: null,
            yDisplayValue: '' },
          { name: 'c-g_mLqJMMC9',
            xId: 'grid-O3kuxDa3J3/i-Vm5jClYsya',
            y: null,
            yDisplayValue: '' },
          { name: 'c-OhD-_zEJ0d',
            xId: 'grid-O3kuxDa3J3/i--TA4VdEqJv',
            y: null,
            yDisplayValue: '' },
          { name: 'c-ihOqTunUxu',
            xId: 'grid-O3kuxDa3J3/i-TJldngJlUC',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c---QRuxKG7F',
       data:
        [ { name: 'c-fdM64DXfTy',
            xId: 'grid-O3kuxDa3J3/i-MBIAt5899k',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-cJucG2hP0G',
            xId: 'grid-O3kuxDa3J3/i-YjPdwF89vL',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-eWlHvq7Dyt',
            xId: 'grid-O3kuxDa3J3/i-UiowRT57C7',
            y: null,
            yDisplayValue: '' },
          { name: 'c-l4A9mlzHbk',
            xId: 'grid-O3kuxDa3J3/i-7etdJDyff2',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xHqrROuF91',
            xId: 'grid-O3kuxDa3J3/i-yurlGnq57y',
            y: null,
            yDisplayValue: '' },
          { name: 'c-PXa-fk6aPe',
            xId: 'grid-O3kuxDa3J3/i-FpP2zazeQV',
            y: null,
            yDisplayValue: '' },
          { name: 'c-yhb9n_ArTN',
            xId: 'grid-O3kuxDa3J3/i-1mEjB9Mycw',
            y: null,
            yDisplayValue: '' },
          { name: 'c-nNMFH1WJLj',
            xId: 'grid-O3kuxDa3J3/i-OIIS_BRwvU',
            y: null,
            yDisplayValue: '' },
          { name: 'c-3_5IsbX7Dw',
            xId: 'grid-O3kuxDa3J3/i-TQsK31CEi8',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: false },
     { name: 'c-RXYWFoYc63',
       data:
        [ { name: 'c-EqBwcgw43A',
            xId: 'grid-O3kuxDa3J3/i-w8weigy_Hf',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-7bOJBSJ2H8',
            xId: 'grid-O3kuxDa3J3/i-s_G4tmqOWJ',
            y: null,
            yDisplayValue: '' },
          { name: 'c-qdmTDUp1i5',
            xId: 'grid-O3kuxDa3J3/i-m1Vyf48dwZ',
            y: null,
            yDisplayValue: '' },
          { name: 'c-f0KyjkraBZ',
            xId: 'grid-O3kuxDa3J3/i-FOgLF6vFc8',
            y: null,
            yDisplayValue: '' },
          { name: 'c-rqupy7OVi9',
            xId: 'grid-O3kuxDa3J3/i-dYv22BT8ez',
            y: null,
            yDisplayValue: '' },
          { name: 'c-Im6jQmJZqA',
            xId: 'grid-O3kuxDa3J3/i-TWvKyOEtqc',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-bEoL9Di1Io',
       data:
        [ { name: 'c-EqBwcgw43A',
            xId: 'grid-O3kuxDa3J3/i-w8weigy_Hf',
            y: 20,
            yDisplayValue: '20' },
          { name: 'c-IQiI9rpd47',
            xId: 'grid-O3kuxDa3J3/i-b4cIbpGMc9',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-yhE5TWWRt-',
            xId: 'grid-O3kuxDa3J3/i-C2dvdaKAkI',
            y: null,
            yDisplayValue: '' },
          { name: 'c-YsJ5H-CJ9r',
            xId: 'grid-O3kuxDa3J3/i-1wwdQmd6ux',
            y: null,
            yDisplayValue: '' },
          { name: 'c-Im6jQmJZqA',
            xId: 'grid-O3kuxDa3J3/i-SbyckjasWM',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-jZMMqkNhhk',
       data:
        [ { name: 'c-xJiVQHweDG',
            xId: 'grid-O3kuxDa3J3/i--26Pjrxoub',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-VW6X3GW2ub',
            xId: 'grid-O3kuxDa3J3/i-b9xuk4dC6O',
            y: null,
            yDisplayValue: '' },
          { name: 'c-Jb8uD7TKHd',
            xId: 'grid-O3kuxDa3J3/i-PtUJP7J3Jr',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xXx2qmI47S',
            xId: 'grid-O3kuxDa3J3/i-zaOjA0WY_p',
            y: null,
            yDisplayValue: '' },
          { name: 'c-g_mLqJMMC9',
            xId: 'grid-O3kuxDa3J3/i-yZpamPqNwy',
            y: null,
            yDisplayValue: '' },
          { name: 'c-3-B_3G2TFk',
            xId: 'grid-O3kuxDa3J3/i-zdMYFG3vs7',
            y: null,
            yDisplayValue: '' },
          { name: 'c-8SKnFa5xfc',
            xId: 'grid-O3kuxDa3J3/i-fFB9AkLMDV',
            y: null,
            yDisplayValue: '' },
          { name: 'c-bGkegIM35g',
            xId: 'grid-O3kuxDa3J3/i-kV4R8pmDBh',
            y: null,
            yDisplayValue: '' },
          { name: 'c-SGqiQqI5qG',
            xId: 'grid-O3kuxDa3J3/i-kSOUcXH8lk',
            y: null,
            yDisplayValue: '' },
          { name: 'c-4U9mQDuAYS',
            xId: 'grid-O3kuxDa3J3/i-J3dHpAC_gw',
            y: null,
            yDisplayValue: '' },
          { name: 'c-ATu4MMN_7h',
            xId: 'grid-O3kuxDa3J3/i-AygI9GYPMp',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-BQG7I7Xw6z',
       data:
        [ { name: 'c-yQzUbrI7iS',
            xId: 'grid-O3kuxDa3J3/i-hBQzbGYqkP',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-cJucG2hP0G',
            xId: 'grid-O3kuxDa3J3/i-YjPdwF89vL',
            y: 50,
            yDisplayValue: '50' },
          { name: 'c-hS1M1DUojg',
            xId: 'grid-O3kuxDa3J3/i-r-lBffTleK',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xHqrROuF91',
            xId: 'grid-O3kuxDa3J3/i-QutvNounKO',
            y: null,
            yDisplayValue: '' },
          { name: 'c--nXgbpdRPt',
            xId: 'grid-O3kuxDa3J3/i-cFfKsMsiz0',
            y: null,
            yDisplayValue: '' },
          { name: 'c-jtafFLci2L',
            xId: 'grid-O3kuxDa3J3/i-BpU2sG5HbU',
            y: null,
            yDisplayValue: '' },
          { name: 'c-Pou8aqID6H',
            xId: 'grid-O3kuxDa3J3/i-ldUn3BMVSf',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-ib3oqJomwg',
       data:
        [ { name: 'c-PXliQA6m0c',
            xId: 'grid-O3kuxDa3J3/i-SHi-KfU74s',
            y: null,
            yDisplayValue: '' },
          { name: 'c-on7iyITyzX',
            xId: 'grid-O3kuxDa3J3/i-VKGTNdwjtI',
            y: null,
            yDisplayValue: '' },
          { name: 'c-UAhTCfxWdg',
            xId: 'grid-O3kuxDa3J3/i-VHoBJDhsss',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xFQSqcpaPL',
            xId: 'grid-O3kuxDa3J3/i-pahTK0EHaE',
            y: null,
            yDisplayValue: '' },
          { name: 'c-3UOc_xkPXA',
            xId: 'grid-O3kuxDa3J3/i-idgLjrEKjf',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-lt7O8RfYp4',
       data:
        [ { name: 'c-ldjTuzYyLk',
            xId: 'grid-O3kuxDa3J3/i-48qvqk3RaL',
            y: null,
            yDisplayValue: '' },
          { name: 'c-3vHrOpTy0u',
            xId: 'grid-O3kuxDa3J3/i-GzW1ZCZciO',
            y: null,
            yDisplayValue: '' },
          { name: 'c-xHqrROuF91',
            xId: 'grid-O3kuxDa3J3/i-3q75Vo9sUe',
            y: null,
            yDisplayValue: '' },
          { name: 'c-eseuXgJ3yu',
            xId: 'grid-O3kuxDa3J3/i-o7aFMGK6al',
            y: null,
            yDisplayValue: '' },
          { name: 'c-w5UvAvlzy2',
            xId: 'grid-O3kuxDa3J3/i-eqzf62k_ke',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-MotjTCAKtw',
       data:
        [ { name: 'c-QgImvOKMDQ',
            xId: 'grid-O3kuxDa3J3/i-Ou_5kvtRYH',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-XEspgaR47Z',
       data:
        [ { name: 'c-rdT0_F0bpH',
            xId: 'grid-O3kuxDa3J3/i-qOyVc0M3JX',
            y: null,
            yDisplayValue: '' },
          { name: 'c-dDhxTki8iv',
            xId: 'grid-O3kuxDa3J3/i-V_hNAbE911',
            y: null,
            yDisplayValue: '' },
          { name: 'c-dGbOYxsuSR',
            xId: 'grid-O3kuxDa3J3/i-FVV7rc9cNN',
            y: null,
            yDisplayValue: '' },
          { name: 'c-Rzd2bJX42Y',
            xId: 'grid-O3kuxDa3J3/i-JXF7TuGy--',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-yJV_JYBKZ3',
       data:
        [ { name: 'c-IiZDunqozI',
            xId: 'grid-O3kuxDa3J3/i--TcbtytOi9',
            y: null,
            yDisplayValue: '' },
          { name: 'c-IiZDunqozI',
            xId: 'grid-O3kuxDa3J3/i-5-tDBy9cts',
            y: null,
            yDisplayValue: '' },
          { name: 'c-IiZDunqozI',
            xId: 'grid-O3kuxDa3J3/i-T_SQSG-q33',
            y: null,
            yDisplayValue: '' },
          { name: 'c-IiZDunqozI',
            xId: 'grid-O3kuxDa3J3/i-IVrsltaZfH',
            y: 50,
            yDisplayValue: '50' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-YebPTYF3yV',
       data:
        [ { name: 'c-H6YVhAeXcV',
            xId: 'grid-O3kuxDa3J3/i-hK3NYhF3T1',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-mhNuDhedQZ',
       data:
        [ { name: 'c-mhNuDhedQZ', xId: '', y: null, yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-AE2Wo2tdPU',
       data:
        [ { name: 'c-i1tFMWdUws',
            xId: 'grid-O3kuxDa3J3/i-W4sfo7WZsY',
            y: null,
            yDisplayValue: '' },
          { name: 'c-QslUKiO3De',
            xId: 'grid-O3kuxDa3J3/i-umi-sYUvvO',
            y: null,
            yDisplayValue: '' },
          { name: 'c-UISl-4Y8W_',
            xId: 'grid-O3kuxDa3J3/i-saDIW_uEBK',
            y: null,
            yDisplayValue: '' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true },
     { name: 'c-NqFlR18g_s',
       data:
        [ { name: 'c-D37zAtneVp',
            xId: 'grid-O3kuxDa3J3/i-Z3aGWfZr4V',
            y: 50,
            yDisplayValue: '50' } ],
       valueColumnId: 'c-v4yKs0L6NP',
       visible: true } ],
  title: { text: null },
  plotOptions:
   { series:
      { stacking: 'normal',
        connectNulls: false,
        dataLabels:
         { style:
            { color: '#444444',
              fontSize: '14.66px',
              lineHeight: '18px',
              fontWeight: 400,
              fontFamily:
               '\'Source Sans Pro\', \'Source Sans\', \'Open Sans\', \'Calibri\', \'BlinkMacSystemFont\', \'Helvetica Neue\', sans-serif' },
           useHTML: true },
        events: {} } },
  chart:
   { type: 'column', backgroundColor: '#fafafa', zoomType: 'xy' },
  legend:
   { enabled: true,
     itemStyle:
      { color: '#444444',
        fontSize: '14.66px',
        lineHeight: '18px',
        fontWeight: 400,
        fontFamily:
         '\'Source Sans Pro\', \'Source Sans\', \'Open Sans\', \'Calibri\', \'BlinkMacSystemFont\', \'Helvetica Neue\', sans-serif' },
     maxHeight: 85 },
  credits: { enabled: false },
  exporting: { buttons: { contextButton: { enabled: false } } },
  tooltip:
   { backgroundColor: '#ffffff',
     borderColor: '#ffffff',
     borderRadius: 8,
     useHTML: true,
     outside: true } });
```
#### Product version
Highcharts 6.0.2 and 7

#### Affected browser(s)
Chrome latest

**Comment by sebastianbochan** [comment]
Hi @jason-krypton,
Thank you for reporting about the problem. Its caused by the using the same name of category multple times (xAxis.categories). As a result when values cannot properly detect where should be stacking.

Example:
```
data: [{
          //name: 'c-IiZDunqozI',
          xId: 'grid-O3kuxDa3J3/i--TcbtytOi9',
          y: null,
          yDisplayValue: ''
        },
        {
          name: 'c-IiZDunqozI',
          xId: 'grid-O3kuxDa3J3/i-5-tDBy9cts',
          y: null,
          yDisplayValue: ''
        },
        {
          name: 'c-IiZDunqozI',
          xId: 'grid-O3kuxDa3J3/i-T_SQSG-q33',
          y: null,
          yDisplayValue: ''
        },
        {
          name: 'c-IiZDunqozI',
          xId: 'grid-O3kuxDa3J3/i-IVrsltaZfH',
          y: 50,
          yDisplayValue: '50'
        }
      ]
```

**The solution:**
- use unique name of categories (one time per name)
- use index of category instead of name 

```
{
          x: 40,
          xId: 'grid-O3kuxDa3J3/i--TcbtytOi9',
          y: null,
          yDisplayValue: ''
}
```

**Internal note**
Should we consider it as a bug?

**Comment by pawelfus** [comment]
It's a bug. It's caused directly by `null` points. 

**Workaround:**
Remove null points from the dataset: https://jsfiddle.net/BlackLabel/zeLsy7qx/1/

*Internal note:*
To be specific, it's caused by `stackIndicator` which is incremented for each point at the same category, but when we read from stack, we read only when point is not null. So two possible solution for a fix:

a) Here, do as the comment says, loop over non-null y-values:
https://github.com/highcharts/highcharts/blob/d325976788f178f83397822a0660a6d516f952ff/js/parts/Stacking.js#L448-L456

b) Calculate `stackIndicator`, before checking if `point.isNull` here:
https://github.com/highcharts/highcharts/blob/d325976788f178f83397822a0660a6d516f952ff/js/parts/Series.js#L3644-L3655
-> 
```javascript
// Calculate the bottom y value for stacked series
if (stacking) {
    stackIndicator = series.getStackIndicator(
        stackIndicator,
        xValue,
        series.index
    );
}

if (
    stacking &&
    series.visible &&
    !point.isNull &&
    stack &&
    stack[xValue]
) {
    pointStack = stack[xValue];
    stackValues = pointStack.points[stackIndicator.key];
    yBottom = stackValues[0];
    yValue = stackValues[1];
    ...
}
```

**Comment by ruaneg** [comment]
I seem to be running into the same error at the same location. 

I've tried the fix in the _bugfix/10160-stacking-null-point_ PR at the moment but its not resolving the issue.
https://github.com/highcharts/highcharts/commit/4373a2702e04fad53a22b75367fcfd185a1e241b

This is a replication of the issue running on our current version 6.0.7:
https://jsfiddle.net/ruaneg/2g3znhab/5/

I have being able to get rid of the error message and get the charts to render by adding a null check _hack_ around the code throwing the error.

https://github.com/highcharts/highcharts/blob/d325976788f178f83397822a0660a6d516f952ff/js/parts/Series.js#L3658-L3659

```
            if(stackValues !== null){
              yBottom = stackValues[0];
              yValue = stackValues[1];
            }
```

Any guidance would be appreciated, on whether this is another bug or just a coincidence and malformed series data.

Thanks

**Comment by pawelfus** [comment]
Thanks for the demo! You are right, it looks like we need a more detailed solution @ppotaczek

**Comment by ruaneg** [comment]
I've created a new fiddle with a smaller data set:
https://jsfiddle.net/ruaneg/65eronp3/22/

The working data objects in the data array, contain 1 object and 4 nulls. The particular object causing the error contains 2 objects and 3 nulls. If I replace the "SIP" object with null it works fine. 

```
		"categories": ["GTP_V2C", "SIP", "SIP_TCP", "DIAMETER", "DIAMETER-SCTP"]
....
{
		"name": "020316838",
		"data": [{
			"name": "GTP_V2C",
			"tooltipData": {
				"buckets": [{
					"name": "Application",
					"value": "GTP_V2C"
				}, {
					"name": "Sub Test",
					"value": "020316838"
				}]
			},
			"y": 17.77,
			"value": 2270,
			"totalValue": 12773
		}, {
			"name": "SIP",
			"tooltipData": {
				"buckets": [{
					"name": "Application",
					"value": "SIP"
				}, {
					"name": "Sub Test",
					"value": "020316838"
				}]
			},
			"y": 20.66,
			"value": 847,
			"totalValue": 4099
		}, null, null, null],
		"allowContextMenu": true
	}
```

**Comment by ruaneg** [comment]
Ive opened a duplicate of this issue as the merged fix is not resolving the issue for our use case.
https://github.com/highcharts/highcharts/issues/10250

**Comment by ruaneg** [comment]
Fixed -> https://github.com/highcharts/highcharts/issues/10250#issuecomment-469647864

**Comment by langen** [comment]
With these merged fixes, we are still seeing some issues as reported here, https://github.com/highcharts/highcharts/issues/10412
