### ISSUE TITLE
Multi-[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event ++

### ISSUE THREAD

**Issue by slashvortal** [highcharts/highcharts#11353]
### Situation
**On MacOS/Chrome**
_CandleStick: When the StockTools are enabled_
Lot of noticeable non proper handled eventListners thrown in the console. mainly refers to touchstart event
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.`

### To reproduce
This can be easily noticeable in the console of any react-based demo of StockChart with enabled stock-toos module.

Here is a quick live demos:
https://codesandbox.io/s/10yv629397
https://www.highcharts.com/stock/demo/stock-tools-gui

Video:
https://i.imgur.com/Z80XISw.mp4

<img width="1054" alt="Screenshot 2019-07-08 at 16 38 38" src="https://user-images.githubusercontent.com/10398252/60887606-1634f500-a255-11e9-8c8f-e4b2e56bd849.png">

**Tested on**
MacOS (Mojave) Chrome (Version 75.0.3770.100) and other Mac machines and Chrome versions.

**Comment by pawelfus** [comment]
Thanks for reporting!

@sebastianbochan - could you take a look?

**Comment by sebastianbochan** [comment]
**Internal note**
In the stockTools we add events (click / touch) by default `H.addEvent`. In the function we should add support of `{passive: true}` for touch events.

- https://developer.mozilla.org/pl/docs/Web/API/Element/addEventListener

**Comment by slashvortal** [comment]
Is there any quick workaround till you add passive support?

**Comment by sebastianbochan** [comment]
Hi @slashvortal,
At this moment you can overwrite the `H.addEvent` function, but, what is important, it requires to be in correct place (before loading modules).

Demo:
- https://jsfiddle.net/BlackLabel/x3c7w2mv/

**Comment by slashvortal** [comment]
Thanks @sebastianbochan, I would wait for the fix so I can use it with highcharts-react wrapper.

**Comment by pjanaya** [comment]
Any plans to fix this yet? The workaround demo linked by @sebastianbochan still shows 21 event-related violations to me.

<img width="559" alt="Screen Shot 2019-11-28 at 11 22 40" src="https://user-images.githubusercontent.com/5021038/69802491-9b538300-11d1-11ea-9352-1c61342ea6d1.png">

**Comment by pawelfus** [comment]
Hi @pjanaya 

Unfortunately we haven't had time to prioritize this yet.

**Comment by pjanaya** [comment]
@pawelfus Ok, thanks. Maybe you should consider removing the "Has workaround" label? Since, at least for me, the workaround doesn't seem to be enough to eliminate the errors.

**Comment by pawelfus** [comment]
*Internal note:*
It's a general issue, not Highstock only. We need to verify if all warnings are correct, sometimes we do need `preventDefault()` and sometimes we can not promise that a developer won't call `preventDefault()` through one of the callbacks.

**Comment by dave-brown755** [comment]
Hi All, is there any update on this issue?

**Comment by sebastianbochan** [comment]
Hi @dave-brown755,
At this moment we are not working on this case, so we do not have new information about. Have you tried to use our workaround?

**Comment by dave-brown755** [comment]
Hi, I didn't try any workaround as there appeared to be a subsequent post asking for the workaround label to be removed.  Are you able to outline the exact steps that need to be followed to implement the workaround to allow the error to be removed.  This is significantly impacting browser performance for ourselves I don't want to move away from high charts but we will not be able to live with the amount of errors being generated.  Hope you can help.  Thanks Dave.

**Comment by sebastianbochan** [comment]
Thank you for the feedback. I added the `inbox label` which means that the ticket is prioritized.

**Comment by dave-brown755** [comment]
Hi, any update on the priority of the ticket?

**Comment by pawelfus** [comment]
Hi @dave-brown755 - this is already prioritized.

**Comment by onur-celik** [comment]
I am waiting for this to be fixed too

**Comment by dave-brown755** [comment]
I could see the ticket had been prioritized but was asking what this means, what is the typical lead time for a ticket that has been given a priority?

**Comment by pawelfus** [comment]
That means ticket will be picked up once current assignments are finished. I expect this issue to be fixed in v8.0.1 or v8.0.2.

**Comment by raf18seb** [comment]
I don't see any warnings in the console anymore (newest Chrome 80). Tested on 3 machines (Mac and Windows 10). Can someone confirm whether the issue still occurs and provide the exact steps to reproduce it?

**Comment by beans9** [comment]
I'm using v8.0.2 but I still see this message. :(

**Comment by pawelfus** [comment]
Just a clarification note: v8.0.1 was released (and v8.0.2) and v8.0.3 will be released shortly because of other critical bugs. Not related to the releasing schedule I expected when I said that I expect issue to be fixed in v8.0.2.

@raf18seb tried to debug the issue a few days ago, but could't recreate this. Any more details (os + chrome version) or new live demo - highly appreciated.

**Comment by MitchellFry** [comment]
@pawelfus we're also seeing this violation, with the latest version 8.0.4. We're rolling back to 5.0.11 where the issue doesn't exist but are looking to update this as soon as we can.

@onur-celik posted a link above where the issue is present for debugging. https://piyasa.paratic.com/

I'm using a Mac with Chrome 80.

**Comment by pawelfus** [comment]
Thanks! I can see these two errors. Both events can be blocking - e.g. when you move your finger around the chart to see the tooltip, then you don't want to scroll your page. Chrome shouldn't show this violation (according to spec, `passive: true` is set by default..).

@raf18seb - could you check once again? Maybe it's OS-dependant issue?

**Comment by raf18seb** [comment]
I confirm, I am able to reproduce it now - I have the same errors in the console on Windows.

**Comment by jllim97** [comment]
hi, is this issue solved? any solution for this issue? I am facing this same issue when using highchart to get complex data from API

**Comment by sebastianbochan** [comment]
The issue has not been solved yet. At this moment we do not have ETA for this ticket, but is in our high priority group of tickets.

**Comment by jllim97** [comment]
okay, thanks for the reply

**Comment by richardeschloss** [comment]
Hi I appreciate your help with this. I too am encountering this, not a major issue for me at the moment but...for people who use the Nuxt framework, Nuxt throws a warning after generating the static pages (and warns that in Nuxt 3.x, the generate will throw a fatal error). So we have time.

**Comment by rocklan** [comment]
I'd also really appreciate a fix for this or just a note of when it might be released.

**Comment by onur-celik** [comment]
I am glad to see this issue "in progress" :)

**Comment by sharmankita** [comment]
You have mentioned fixed here. When can these changes be applied in CDN versions.

**Comment by pawelfus** [comment]
Hi @sharmankita - issue still has `in progress` label. That means it's not fixed, we are still working on it.

**Comment by violetVo** [comment]
Hi, any update on this? Is there an ETA for the fix?

**Comment by pawelfus** [comment]
Hi @violetVo - no ETA, we are still working on this.

**Comment by richardeschloss** [comment]
What happens when the event is marked as "passive"?
```js
elm.on("touchstart", function(ev) {
  // stuff
}, {
  passive: true // does this option help?
});
```

**Comment by pawelfus** [comment]
I'm not sure what do you mean @richardeschloss - could you elaborate? I will try to answer your questions one by one:

> What happens when the event is marked as "passive"?

See description here: https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener

> passive: true // does this option help?

This won't work in IE and Safari on iOS.

**Comment by richardeschloss** [comment]
Pawel, it seems like Rafal has got this one fixed. I saw the PR which helps answer the question I had. thanks.

**Comment by onur-celik** [comment]
finally 🥰

**Comment by violetVo** [comment]
Hi,
Thanks for the fix! Is it available in version 8.2.2?

**Comment by pawelfus** [comment]
Hi @violetVo v8.2.2 was released ~2 weeks ago. Fix will be available in the next release.

**Comment by forgivegod** [comment]
@pawelfus  do you have a timeframe for the next release? Just wondering.  
Hope you and the team are safe (re: covid)!

**Comment by pawelfus** [comment]
Thank you @forgivegod, we are good 👍  I hope you are good too!

The next release should be ready within a few weeks

**Comment by onur-celik** [comment]
bug fixed?

**Comment by KacperMadej** [comment]
Fixed since v9.0.0.

**Comment by AlexandruCardas** [comment]
Hi, I am using highcharts 9.0.1 and I am building a website using Gatsby, this issue still comes up when I am running a lighthouse report...
