### ISSUE TITLE
split tooltip and scrollbalePlotArea

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#11617]
#### Expected behaviour
Tooltip with full opacity

#### Actual behaviour
Tooltip hidden behind the scrollable mask

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/jbk9qpnx/

Scroll down to the xAxis and hover any point.

Screenshot:

![Screen Shot 2019-08-06 at 14 56 35](https://user-images.githubusercontent.com/1453926/62541617-6904cb00-b85a-11e9-824e-067a83d6bb01.png)

#### Product version
v7.1.2

**Comment by AntonyJos** [comment]
@jon-a-nygaard , Would you mind looking at this issue for quick assessment?

**Comment by pawelfus** [comment]
**Workaround:**
Move tooltip's header into the plotting area using [`tooltip.positioner`](https://api.highcharts.com/highcharts/tooltip.positioner) - it's not perfect, but at least tooltip is visible, demo: https://jsfiddle.net/BlackLabel/td5jo3pf/

Snippet:
```js
  tooltip: {
    split: true,
    positioner: function(w, h, p) {
      var ret;
      if (this.split) {
        if (p.isHeader) {
          ret = {
            x: p.plotX,
            y: p.plotY - h
          };
        } else {
          ret = {
            x: p.plotX,
            y: p.plotY - h
          };
        }

      } else {
        ret = this.getPosition(w, h, p);
      }

      return ret;
    }
  },
```

**Comment by jon-a-nygaard** [comment]
**Internal Note:** Seems that adding support for `tooltip.outside` with `tooltip.split: true` could be a solution to this issue [ts/parts/Tooltip.ts#L376-L387](https://github.com/highcharts/highcharts/blob/a20ef03ccad60ca546f60d638ccff3c1089384ea/ts/parts/Tooltip.ts#L376-L387)

**Comment by jon-a-nygaard** [comment]
I will start implementing support for `tooltip.outside` in split tooltip, which I believe should also solve this issue. For information on progress for this implementation please see related issue #9590.

**Comment by AntonyJos** [comment]
@jon-a-nygaard / @TorsteinHonsi 

The defect 9590 seems to be in closed state as of now..
Does those fixes seem to resolve this issue as well?

**Comment by TorsteinHonsi** [comment]
Yes, as you can see if we apply the latest code from the master, `split` and `outside` now work in combination: http://jsfiddle.net/highcharts/xyzLtgkr/

**Comment by AntonyJos** [comment]
Observed multiple behavior for the fix provided

_Behavior 1_ (**expected**)

![Behaviour 1](https://user-images.githubusercontent.com/42953694/65406387-07de8a00-ddfd-11e9-907b-63c21ee36842.png)

_Behavior 2_ (**tooltip Header missing**)

![Behaviour 2](https://user-images.githubusercontent.com/42953694/65406499-686dc700-ddfd-11e9-87f5-e87a212d0ffd.png)

_Behavior 3_ (**tooltip displayed outside the plotarea**)

![Beahavior 3](https://user-images.githubusercontent.com/42953694/65406586-99e69280-ddfd-11e9-9dbc-681f5e48f0ce.png)

**Comment by AntonyJos** [comment]
@TorsteinHonsi  and @jon-a-nygaard ,

Kindly revisit the defect to have a perfect fix

**Comment by jon-a-nygaard** [comment]
Thanks for the feedback @AntonyJos, I will continue working on this. At first sight it seems to be some compatibility issue with the scroll container and the outside tooltip container.

**Comment by jon-a-nygaard** [comment]
Hi @AntonyJos, it is still work in progress.
There is many variables to factor in with both the scroll container and the outside tooltip to get the positioning just right. It is taking some time to get it proper, but I believe I am closing in on a solution.

I will let you know as soon as I have more information or something to show.

**Comment by jon-a-nygaard** [comment]
Hi @AntonyJos, I have added a PR #12324 that should fix this issue. There is some examples added where you can see the new behavior.
The PR is currently in review, and if it passes all checks and is accepted, then it will be included in the next maintenance release.

**Comment by AntonyJos** [comment]
@jon-a-nygaard I guess the issue still exists with  highstock

**Comment by AntonyJos** [comment]
link : https://jsfiddle.net/highcharts/qsomL4kz/2/

**Comment by AntonyJos** [comment]
![highstock tooltip](https://user-images.githubusercontent.com/42953694/68766422-d0de6500-0644-11ea-82d2-9333785fa697.png)

Kindly verify

**Comment by jon-a-nygaard** [comment]
Hi @AntonyJos,

Yes, this is because current version 7.2.1 was released before this issue was fixed. The issue should be fixed in the master branch, as you can see at https://jsfiddle.net/jon_a_nygaard/8sgLod19/, and will be included in the upcoming release.

**Comment by AntonyJos** [comment]
Thanks @jon-a-nygaard for the correction.
i guess compatibility issue with the scroll container and the outside tooltip container is resolved.

But i do see a **new issue**

The tool-tip positions for individual axis are not being updated while scrolling

![tooltip Position](https://user-images.githubusercontent.com/42953694/68854424-072dea00-0702-11ea-9c47-eda495ec0de4.png)

Fiddle Link : https://jsfiddle.net/Loepjy94/1/

Also, Hope you remember the fix made as part of the defect
_https://github.com/highcharts/highcharts/issues/11493_

I believe this fix is no more in effect with the current changes, since split tool tip was supposed to be limited to the y -Axis range which does not seem to be the case with scrollablePlotArea enabled

@jon-a-nygaard , Please check this as well.

**Comment by jon-a-nygaard** [comment]
> The tool-tip positions for individual axis are not being updated while scrolling

Thanks @AntonyJos, I have submitted a new issue to keep the scope of issue clear. You can follow its progress at #12416 

> Also, Hope you remember the fix made as part of the defect
#11493
> I believe this fix is no more in effect with the current changes

This issue has been taken into account.
The tooltip labels itself is not limited to within the axes, as we considered that this will be a regression of the existing tooltip behavior, see https://jsfiddle.net/jon_a_nygaard/wsf9ovgn/5/.
The fix for the other issue unfortunately introduced this regression in split tooltip, which is why it has been adjusted in the current PR.

The anchor (target position) of the tooltip labels however is still restricted to within the axes. So the tooltip labels will not be misaligned or point to incorrect positions as it did prior to the fix for #11493.

Please let us know if you have thoughts or suggestion about this behavior.
