### ISSUE TITLE
Highstock/Highcharts v 7.2.1 introduced scrolling bug with scatter plots

### ISSUE THREAD

**Issue by briangroelinger** [highcharts/highcharts#12658]
#### Expected behaviour
Scroll down the page to a scatter plot graph and hover over a point on the graph, have it highlight/select the correct data point

#### Actual behaviour
Scrolling down on the page quickly, having the cursor land over the graph and moving it to different points on the graph will actually highlight the wrong point.  When clicking on it or looking at the tooltip, it is on a different point in the graph.  This doesnt happen 100% of the time, but about 30%. 

When you take you mouse outside of the graph div and bring it back in, it will fix itself most of the time, but not all of the time.  Scrolling back up and taking the mouse out of the div and bringing it back in will also resolve the issue. 

Reverting back to 7.2.0 resolved the issue

#### Live demo with steps to reproduce
Unfortunately do to client confidentiality, there is no real way to give a live demo of our portal, and I fear it is an issue with the number of graphs we are displaying on the page.  

Essentially what i am doing is loading in scatter plot points with setData below the fold through an Ajax call.  After the data has populated the graph, if i scroll quickly from the top of the page to the div where the scatterplot lives and have my mouse land inside the graph after the scroll instead of having to move it inside the div, the point i am trying to select is incorrect. What i mean by incorrect is that the point that highlights/displays the tooltip for is not the point i am hovering over. 

Taking the mouse outside the div and back in will resolve the issue around 50% of the time.  After taking it out and back in more than once, it is usually fixed
 It may be possible to provide a video of some demo data of this, but it would be difficult to reproduce it in a not-real-data kind of way.  

![wrong point](https://user-images.githubusercontent.com/8960558/71039191-952a3580-20f1-11ea-8031-2165b155cf6a.png)

 plotOptions: {

                scatter: {
                    marker: {
                        radius: 5,
                        states: {
                            hover: {
                                enabled: true,
                            }
                        }
                    },

                    states: {
                        hover: {
                            marker: {
                                enabled: false
                            }
                        }
                    },

                    tooltip: {
                      hideDelay: 0,
                      outside:true,
                      followPointer: 'true'
                    }
                },

                series: {

                    cursor: 'pointer',
                    turboThreshold: 0,
                    allowPointSelect: true,
                    stickyTracking: false,
                    animation: false,

                    point: {
                        events: {
                            click: function (event) {
                       
                              this.graphic.toFront();
                              
                        }
                    }
                }
            },
#### Product version
Highstock/Highcharts 7.2.1 and above

#### Affected browser(s)
Using newest version of chrome, not sure if it is happening in all browsers.

**Comment by sebastianbochan** [comment]
Hi @briangroelinger,
Thank you for reporting about the problem. Have you tried to disable the `tooltip.outside` option? Is it possible to share a live demo with us on private supports channel like i.e email?

**Comment by briangroelinger** [comment]
I took all of the tooltip changes out and put them in the tooltip section where they belong, i then removed the outside, follow pointer, and hide delay options and the problem still persists.  I am able to reproduce this issue more consistently by scrolling while moving the mouse horizontal instead of vertical.  

 I may be able to get on for a live demo sometime tomorrow.  

For right now, I am just reverting back to Highstock 7.2.0 and the problem goes away.

**Comment by pawelfus** [comment]
Perhaps it's the same issue as #12657?

**Comment by briangroelinger** [comment]
sorry I have been out on vacation and am just now getting back to my emails - #12657 seems like a similar issue as what I am having.  

But just to be clear, it isn't just the tooltip that is displaying incorrectly. It is actually selecting the incorrect point in the scatterplot.  If you look at the image I included above, you can see that I am hovering over a red triangle, but the green one below it is the one being highlighted.  I have click events attached to these dots and it even behaves as if I clicked the highlighted point, not the one I am hovering over. 

If there is still interest in seeing a live demo, I should be available pretty much any day  8am - 5:30pm EST.

**Comment by pawelfus** [comment]
Thanks for getting back to the issue. If you use [chart.scrollablePlotArea](https://api.highcharts.com/highcharts/chart.scrollablePlotArea) then it's duplicate of #12657 (wrong point is highlighted). It might be a different issue though, #12675 happens always when scrolled.

Given the scenario description, this might be something different - could you add [`boost`](https://code.highcharts.com/modules/boost.src.js) module to your project and set [`series.boostThreshold = 1`](https://api.highcharts.com/highcharts/series.line.boostThreshold) ? 

Additionally check if [`series.findNearestPointBy`](https://api.highcharts.com/highcharts/series.scatter.findNearestPointBy) is not changed to `x`.

> If there is still interest in seeing a live demo, I should be available pretty much any day 8am - 5:30pm EST.

Unfortunately, this won't help us. We always ask for a live demo (jsFiddle/stackblitz) because then we can use our tools to debug and fix the issue. Also we can use that demo as a regression test to avoid introducing regression again etc.

**Comment by briangroelinger** [comment]
the issue with boost is  

> - Marker shapes are not supported: markers will always be circles

I need shapes do differentiate different data types.  But just for sake of interest, i did apply boost to it and the issue still persisted. For now I will wait for the other similar issue to be addressed and see if it fixes this.

**Comment by pawelfus** [comment]
Hi @briangroelinger - #12675 is fixed (v8.0.1+), are you still able to reproduce the issue in your project? Thanks!

**Comment by briangroelinger** [comment]
Hi,

Unfortunately, it looks like the issue is still occurring with v8.1.0.  I can’t remember how much detail I provided in the past, so I will do my best here to reiterate the issue.

The issue appears to happen after using my mouse wheel or my laptop’s trackpad to scroll down or up to the graph. My mouse is hovering over the selected point (the one with the cursor), but a different point above it is being highlighted on the graph (circled).  The tooltip of the wrong point is being displayed as well.  Any of the points in that general area are actually selecting that same point at the top. As soon as my mouse leaves the graph area and comes back, the points fix themselves and the graph behaves properly.

This is happening for all of my scatter plot graphs where there is a scroll present on the page.  It is happening in Chrome and in Edge (didn’t test other browsers). The only other detail I can think to provide is I am using bootstrap 3 and jquery to build this page.

[cid:image001.png@01D62854.DD2E6EE0]

**Comment by pawelfus** [comment]
Thanks! Could you please test this workaround and let me know the results? The workaround: https://github.com/highcharts/highcharts/issues/13488#issuecomment-627227348

**Comment by briangroelinger** [comment]
YES! It worked, thank you so much!

**Comment by pawelfus** [comment]
Okay, great, thank you!
Since #13488 has more details (incl. live demo), let me close this ticket as a duplicate of #13488.
