### ISSUE TITLE
Tooltip not displaying correctly for points in line chart after scrolling

### ISSUE THREAD

**Issue by gopi-it** [highcharts/highcharts#12657]
#### Expected behaviour
When line charts are scrolled and the markers are clicked after scrolling tooltip for the relevant marker should be displayed but the tooltip for other markers are displayed. Mentioned below the screenshot for reference.

In the below image, when i click on the marker at Year 11 after scrolling through the chart horizontally , the tooltip for the Year 5 is being displayed, i expect to view the tooltip for the Year 11. This issue is not happening in 6.2.0 version but occuring in higher version like 8.0.0
![image](https://user-images.githubusercontent.com/20495411/71033982-622e7480-20e6-11ea-8d5a-900d4c8d2573.png)

This issue also occurs when i change the toggle the chrome browser to mobile, tab views

#### Live demo with steps to reproduce
https://jsfiddle.net/gopi07it/o3adqbns/11/

#### Product version
8.0.0

#### Affected browser(s)
Chrome, IE, Firefox

**Comment by KacperMadej** [comment]
Hi @gopi-it 

Thank you for reporting the problem.

This is a regression. The last working version is 7.1.1. Demo: https://jsfiddle.net/BlackLabel/2dya7uw6/

**Comment by pawelfus** [comment]
Bisected to commit 8359afc222

**Comment by pawelfus** [comment]
Fixed since v8.0.1: https://jsfiddle.net/BlackLabel/81esbqva/

**Comment by MarkJungeblut** [comment]
@pawelfus 
https://github.com/highcharts/highcharts/issues/13182 

The issue was closed as duplicate to this here but the error still persist with v.8.0.1

https://jsfiddle.net/bm5ycuve/7/
The issue is present since v7.2.1, v8.0.*

We also got an alert that cross side scripting is possible since v.7.2.0 but we cannot upgrade until the problem is fixed.

**Comment by KacperMadej** [comment]
Let's reopen the issue with more info about the existing problem and keep this one closed. I will add the correct labels there.

**Comment by MarkJungeblut** [comment]
@KacperMadej Sounds great! 
Thank you. 
If you need some more information dont hesitate to contact me.

**Comment by MarkJungeblut** [comment]
@KacperMadej Are there any news about the problem? 
I saw that the issue is still closed. 

When can we expect a fix for the problem?

**Comment by pawelfus** [comment]
Hi @MarkJungeblut 

Ticket #13182 is still open. Just tried to recreate the issue from #13182 but I'm not able to. Can you check it once again?

PS: Let's continue the discussion in #13182
