### ISSUE TITLE
The HighMap Demo "Map With overlaid pie charts" is not working

### ISSUE THREAD

**Issue by OscarsLopez** [highcharts/highcharts#13442]
#### Expected behaviour
The map is shown in the Demo page, with the overlap pies. The demo URL is:
https://www.highcharts.com/maps/demo/map-pies

#### Actual behaviour
The map does not work and only the series labels are shown. There is an error in the browser console with the next text:

highcharts.src.js:32152 Uncaught TypeError: Cannot read property 'dataMin' of undefined

Others Demos have the same issue.

#### Live demo with steps to reproduce
https://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/maps/demo/map-pies/

#### Affected browser(s)
Chrome, Edge maybe others.

**Comment by nobleclem** [comment]
I have been tracking down this exact issue and submitted an email to their support account and it has to do with v8.1.0 being released today where code.highcharts.com/highcharts.js is at v8.1.0 and code.highcharts.com/maps/modules/map.js is at v8.0.4

Oddly enough code.highcharts.com/highcharts.src.js is at v8.0.4 so when it is used highmaps works.

**Comment by sebastianbochan** [comment]
We're just releasing all files and now all of them should be updated to 8.1.0 version.

**Comment by madepiet** [comment]
As mentioned, this is a problem related to the upgrade of the new version of Highcharts, in my case, it helped to clear the browser cache.

**Comment by nobleclem** [comment]
I guess I don't know what the deploy process is like but it taking hours is problematic for people.  For HOURS all of our implementation of highmaps was broken.  Seems like there could be a better way of preparing new versions and deploying them where everyone is seeing the same version in the future.

**Comment by pawelfus** [comment]
Hi @nobleclem 

> I guess I don't know what the deploy process is like but it taking hours is problematic for people.

We are sorry for the issue - it has happened for the first time. It shouldn't happen in future. Deploying process does not take much time, as soon as we noticed the issue - we fixed it.

> For HOURS all of our implementation of highmaps was broken. 

Maintenance-wise it's better to use specific version (or range of versions), not the most recent one (https://code.highcharts/8.0/highcharts.js and https://code.highcharts.com/7/highcharts.js 
 vs https://code.highcharts.com/highcharts.js). Otherwise, you will have no time to follow our upgrade notes for breaking changes listed in our changelog.. (link: https://www.highcharts.com/blog/changelog/). You can use our CDN just like described here: http://code.highcharts.com/

**Comment by pawelfus** [comment]
Closing issue as fixed.

**Comment by waiz3ple** [comment]
I'm still getting this error when I  am trying to use map and gauge on a page

**Comment by pawelfus** [comment]
Hi @waiz3ple 

If your encounter this issue with map and gauge series, then please contact our support team: https://www.highcharts.com/blog/support/
