### ISSUE TITLE
Highstock zoomed range doesn't update when adding points to secondary series

### ISSUE THREAD

**Issue by ntenisOT** [highcharts/highcharts#1347]
I have a big problem with HighCharts, HighStock and live data / live chart.

Please check :

http://jsfiddle.net/5RutC/160/

and try to remove the 1st of series (Random Data). The chart will stop updating. If you reselect the 1st of the series it will continue updating with all values.

Is it possible to somehow overcome this or is a bug with HighChats/HighStock?

Thanks in advance

**HTML Code:**

```
<script src="http://code.highcharts.com/stock/highstock.js"></script>
<script src="http://code.highcharts.com/stock/modules/exporting.js"></script>

<div id="container" style="height: 500px; min-width: 500px"></div>​ 
```

**Javascript Code:**

```
$(function() {

    Highcharts.setOptions({
        global : {
            useUTC : false
        }
    });

    // Create the chart
    window.chart = new Highcharts.StockChart({
        chart : {
            renderTo : 'container',
            events : {
                load : function() {

                    // set up the updating of the chart each second
                    var series = this.series[0];
                    var series1 = this.series[1];
                    var chart = this;
                    setInterval(function() {
                        var x = (new Date()).getTime(), // current time
                        y = Math.round(Math.random() * 100);
                        y1 = Math.round(Math.random() * 100);
                        series.addPoint([x, y], false, true);
                        series1.addPoint([x, y1], false, true);
                        chart.redraw();
                    }, 1000);
                }
            }
        },

        rangeSelector: {
            buttons: [{
                count: 1,
                type: 'minute',
                text: '1M'
            }, {
                count: 5,
                type: 'minute',
                text: '5M'
            }, {
                type: 'all',
                text: 'All'
            }],
            inputEnabled: false,
            selected: 0
        },

        title : {
            text : 'Live random data'
        },
        legend: {
                align: 'right',
                layout: 'vertical',
                verticalAlign: 'top',
                y: 45,
                enabled: 'true'
            },

        exporting: {
            enabled: false
        },

        series : [{
            name : 'Random data',
            data : (function() {
                // generate an array of random data
                var data = [], time = (new Date()).getTime(), i;

                for( i = -999; i <= 0; i++) {
                    data.push([
                        time + i * 1000,
                        Math.round(Math.random() * 100)
                    ]);
                }
                return data;
            })()
        },{
            name : 'Random data2',
            data : (function() {
                // generate an array of random data
                var data = [], time = (new Date()).getTime(), i;

                for( i = -999; i <= 0; i++) {
                    data.push([
                        time + i * 1000,
                        Math.round(Math.random() * 100)
                    ]);
                }
                return data;
            })()
        }]
    });

});
```

**Comment by sebastianbochan** [comment]
+1

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
This is another one that seems to be fixed with the refactoring done for #2266. See http://jsfiddle.net/highcharts/5RutC/190/. This means it will be fixed with the next maintenance release.

**Comment by TorsteinHonsi** [comment]
Fixed by a5bd7001f8cf129e1da6b72d43b7c06afdc6efe5

**Comment by sebastianbochan** [comment]
Seems that problem still appears, because the navigator is not updated and when we move handles, points are not added anywhere. Only series "blinks". 

Example:
- http://jsfiddle.net/exr2zs3a/

**Comment by TorsteinHonsi** [comment]
I don't know if it was intentionally, but you added points to the navigator series. If you add to the two main series, the navigator series will follow: http://jsfiddle.net/highcharts/exr2zs3a/1/

**Comment by CrazyFunker** [comment]
@TorsteinHonsi in your last fiddle you are adding points to the first series, which is not how this bug is reproduced. Comment out chart.get(1).addPoint([x, y1], false, true); and you'll see it happen.

**Comment by TorsteinHonsi** [comment]
Ok, here's a simplified demo: http://jsfiddle.net/exr2zs3a/2/. The OP also added data to the navigator series, which confused me. 

The problem is that the Scroller's `stickToMin` and `stickToMax` flags are [updated through the](https://github.com/highcharts/highcharts/blob/v4.2.5/js/parts/Scroller.js#L1095-L1100) `updatedData` event on the base series. The base series is the first series in the chart. So when we update the second series, these are not set. So I tried moving this to the `modifyBaseAxisExtremes` function to pick up changes in all series, but now a lot of tests failed. The current effort can be seen at https://gist.github.com/TorsteinHonsi/9d7b004351d8574e979ab76200d0b6d1.

**Comment by TorsteinHonsi** [comment]
#### Workaround

Since we've placed the data handling too close to the main series, we need to mark the first series dirty, as well as the navigator xAxis before redraw. 

```js
    // Workaround to force update (#1347)
	chart.scroller.baseSeries.isDirtyData = true;
    chart.scroller.xAxis.isDirty = true;
    
    chart.redraw();
```
[View live demo at jsFiddle](http://jsfiddle.net/highcharts/exr2zs3a/4/).

**Comment by pawelfus** [comment]
Another workaround (with a bit different output):

Set [`series.showInNavigator`](http://api.highcharts.com/highstock/plotOptions.series.showInNavigator) for all series to true : [demo](http://jsfiddle.net/exr2zs3a/5/)
