### ISSUE TITLE
Exporting Print button not working

### ISSUE THREAD

**Issue by madepiet** [highcharts/highcharts#13575]
#### Expected behaviour
Correct operation of exporting print button - no errors in the console.

#### Actual behaviour
The exporting print button does not work:
`Uncaught TypeError: Cannot read property 'forEach' of undefined`

#### Live demos with steps to reproduce
The "Area Range" demo on the official site will show the issue as it uses highcharts-more.js: https://www.highcharts.com/demo/arearange  

If you go to the Basic Line demo: https://www.highcharts.com/demo/line-basic,  
it works correctly but if you add highcharts-more.js after highcharts.js and re-run it will not work.

#### Product version
Highcharts v8.1.0

#### Affected browser(s)
Chrome Version 81.0.4044.138

**Comment by madepiet** [comment]
Internal note:
Works well in version 8.0.4:
https://jsfiddle.net/BlackLabel/o1h7m3wc/

It looks like the issue is in code added in highcharts-more.js and networkgraph.js in 8.1.0.

**Comment by madepiet** [comment]
Closed as resolved (corrected in the new version):
https://jsfiddle.net/BlackLabel/a39ptvw7/

**Comment by fcardillo** [comment]
Still have problems on print function, already tried to load the git version on the github.

<script src="https://github.highcharts.com/highcharts.js"></script>
<script src="https://github.highcharts.com/modules/data.js"></script>
<script src="https://github.highcharts.com/highcharts-more.js"></script>
<script src="https://github.highcharts.com/modules/exporting.js"></script>
<script src="https://github.highcharts.com/modules/export-data.js"></script>
<script src="https://github.highcharts.com/modules/accessibility.js"></script>




Uncaught TypeError: Cannot read property 'forEach' of undefined
    at d.Chart.<anonymous> (highcharts-more.src.js:7384)
    at highcharts.src.js:2423
    at d.fireEvent (highcharts.src.js:2428)
    at d.Chart.beforePrint (exporting.src.js:1574)
    at d.Chart.print (exporting.src.js:1658)
    at d.Chart.onclick (mqtt2.js:253)
    at B.z (exporting.src.js:1852)
    at SVGGElement.<anonymous> (highcharts.src.js:6396)
    at SVGGElement.e.onclick (highcharts.src.js:4412)

**Comment by madepiet** [comment]
Hi @fcardillo 
If you still have that problem could you reproduce your simplified, working config in an online editor such as JSFiddle that we could work on? 

Because from what I've tested, it works fine with this fix: 
https://jsfiddle.net/BlackLabel/up5hr6ft/

**Comment by fcardillo** [comment]
http://jsfiddle.net/0f9seymo/1/

 

Follow the correct link, sorry.

 

 

 

My best regards

 

Fabio Cardillo

 

De: Piotr Madej <notifications@github.com> 
Enviada em: quarta-feira, 27 de maio de 2020 06:06
Para: highcharts/highcharts <highcharts@noreply.github.com>
Cc: fcardillo <fabio@easyanalytics.com.br>; Mention <mention@noreply.github.com>
Assunto: Re: [highcharts/highcharts] Exporting Print button not working (#13575)

 

Hi @fcardillo <https://github.com/fcardillo> 
If you still have that problem could you reproduce your simplified, working config in an online editor such as JSFiddle that we could work on?

Because from what I've tested, it works fine with this fix:
https://jsfiddle.net/BlackLabel/up5hr6ft/

**Comment by fcardillo** [comment]
Piotr,

 

I foound the problem, Highcharts was being inserted in another location of the code, I replaced the hicharts-more.js from github link and it worked fine!

 

Sorry about my mistake,

 

 

My best regards

 

Fabio Cardillo

 

De: Easy Analytics <fabio@easyanalytics.com.br> 
Enviada em: quarta-feira, 27 de maio de 2020 09:32
Para: 'highcharts/highcharts' <reply@reply.github.com>; 'highcharts/highcharts' <highcharts@noreply.github.com>
Cc: 'fcardillo' <fabio@easyanalytics.com.br>; 'Mention' <mention@noreply.github.com>
Assunto: RES: [highcharts/highcharts] Exporting Print button not working (#13575)

 

http://jsfiddle.net/0f9seymo/1/

 

Follow the correct link, sorry.

 

 

 

My best regards

 

Fabio Cardillo

 

De: Piotr Madej <notifications@github.com <mailto:notifications@github.com> > 
Enviada em: quarta-feira, 27 de maio de 2020 06:06
Para: highcharts/highcharts <highcharts@noreply.github.com <mailto:highcharts@noreply.github.com> >
Cc: fcardillo <fabio@easyanalytics.com.br <mailto:fabio@easyanalytics.com.br> >; Mention <mention@noreply.github.com <mailto:mention@noreply.github.com> >
Assunto: Re: [highcharts/highcharts] Exporting Print button not working (#13575)

 

Hi @fcardillo <https://github.com/fcardillo> 
If you still have that problem could you reproduce your simplified, working config in an online editor such as JSFiddle that we could work on?

Because from what I've tested, it works fine with this fix:
https://jsfiddle.net/BlackLabel/up5hr6ft/

**Comment by georgii-sirotkin** [comment]
@madepiet When will the fixed version be published to npm?

**Comment by madepiet** [comment]
Hi @georgii-sirotkin 
The fix will be added in the new version, you can expect it in a few weeks.
