### ISSUE TITLE
temporaryDisplay messes up parent DOM

### ISSUE THREAD

**Issue by naksenzh** [highcharts/highcharts#14090]
Regression: #7508

https://github.com/highcharts/highcharts/issues/7508

Expected behavior
Highstock doesn't affect DOM of its container's parent elements

Actual behavior
If the chart is created (or redrawn) when it's hidden, Highstock will call temporaryDisplay, which affects the parent elements' DOM. In particular, I've been having problems where it changes the "important" attribute of "display:none" on a parent element.

Would it be possible to add a setting that tells Highstock never to do this? Maybe in that case it could just delay drawing until it's made visible.

Live demo with steps to reproduce
Affected browser(s)
all

**Comment by naksenzh** [comment]
@oysteinmoseng FYI we still have the same issue and it introduced regression when the team upgrades to the latest highcharts and latest accessibility module

**Comment by oysteinmoseng** [comment]
It looks like there was a workaround in the old issue, but that the issue was never solved in the core. @TorsteinHonsi can probably confirm. The workaround in the old issue seems to still work with the latest version for me. The issue also seems unrelated to the accessibility module - at least in my tests.

@naksenzh Could you try applying the workaround from the old issue and report back? If you are still experiencing issues, would you be able to create a jsFiddle demo for debugging?

**Comment by oysteinmoseng** [comment]
Old issue workaround (run before creating chart):

```javascript
(function (H) {
	var doc = document,
    	each = H.each;
    /** 
	 * If the renderTo element has no offsetWidth, most likely one or more of
	 * its parents are hidden. Loop up the DOM tree to temporarily display the
	 * parents, then save the original display properties, and when the true
	 * size is retrieved, reset them. Used on first render and on redraws.
	 *
	 * @private
	 * 
	 * @param  {Boolean} revert
	 *         Revert to the saved original styles.
	 */
	H.Chart.prototype.temporaryDisplay = function (revert) {
		var node = this.renderTo,
			tempStyle;
		if (!revert) {
			while (node && node.style) {

				// When rendering to a detached node, it needs to be temporarily
				// attached in order to read styling and bounding boxes (#5783,
				// #7024).
				if (!doc.body.contains(node) && !node.parentNode) {
					node.hcOrigDetached = true;
					doc.body.appendChild(node);
				}
				if (
					H.getStyle(node, 'display', false) === 'none' ||
					node.hcOricDetached
				) {
					node.hcOrigStyle = [
						['display', node.style.getPropertyValue('display'),
							node.style.getPropertyPriority('display')],
						
						['height', node.style.getPropertyValue('height'),
							node.style.getPropertyPriority('height')],
						
						['overflow', node.style.getPropertyValue('overflow'),
							node.style.getPropertyPriority('overflow')]
					];
					tempStyle = [
						['display', 'block', 'important'],
						['overflow', 'hidden', 'important']
					];
					if (node !== this.renderTo) {
						tempStyle.push(['height', 0, 'important']);
					}
					
					each(tempStyle, function (prop) {
						node.style.setProperty.apply(node.style, prop);
					});

					// If it still doesn't have an offset width after setting
					// display to block, it probably has an !important priority
					// #2631, 6803
					if (!node.offsetWidth) {
						// node.style.setProperty('display', 'block', 'important');
					}
				}
				node = node.parentNode;

				if (node === doc.body) {
					break;
				}
			}
		} else {
			while (node && node.style) {
				if (node.hcOrigStyle) {
					// H.css(node, node.hcOrigStyle);
					each(node.hcOrigStyle, function (prop) {
						node.style.setProperty.apply(node.style, prop);
					});
					delete node.hcOrigStyle;
				}
				if (node.hcOrigDetached) {
					doc.body.removeChild(node);
					node.hcOrigDetached = false;
				}
				node = node.parentNode;
			}
		}
	};
}(Highcharts));
```

**Comment by naksenzh** [comment]
thanks for the quick response, we will have a look and share the details tomorrow morning within EMEA working hours.

**Comment by umkoksal** [comment]
Hey @oysteinmoseng, I have tried the workaround, and while it does fix the issue of charts being rendered in invisible containers, we now have another issue. 

If a chart is rendered on a section of the screen which is overflown (chart needs to be scrolled to, in order to be seen), it expands it's parent to the point at which it is rendered. I have a jsfiddle demonstrating the issue below:

https://jsfiddle.net/ch79f4rk/1/

See here that even though #mainParent and #parent have a strict height/max-height set, and that #buffer div pushes the chart below the invisible area of the screen (so the chart is rendered outside the screen). What we expect here is that the inner #parent container would display a scrollbar and that would be the only scrollable container, but #mainParent also displays a scrollbar, and this scrollbar gets larger if we increase the width of the #buffer container, even though it's immediate parent's height stays the same.

You can also go ahead and delete the <figure> element that contains the chart, and with everything else staying the same, our expected behavior is achieved (that is, the scrollbar on the outermost parent disappears)

**Comment by oysteinmoseng** [comment]
I see, @TorsteinHonsi any thoughts?

**Comment by naksenzh** [comment]
@oysteinmoseng , @TorsteinHonsi, could you please share the updates? Thanks

**Comment by TorsteinHonsi** [comment]
@umkoksal Sorry for the delay, I've been out of office. In the [draft PR](https://github.com/highcharts/highcharts/commit/452288e4ef9fdc2a328493bcbb02839e8f3e3441), I implemented the same idea as the snippet above. I can't see any double scrollbars like you describe above. Can you have a look at the fix and see if your issue is resolved?

**Comment by umkoksal** [comment]
@TorsteinHonsi, thank you for the quick fix. I have tested our scenarios with the javascript file generated from your PR, alongside our updated modules. The issue still persisted, however I was able to dig deeper and found that the second scrollbar was caused by the two aria-live containers rendered within HighCharts. 

![image](https://user-images.githubusercontent.com/61870580/97013384-49ce8800-1549-11eb-93fe-7305d651747f.png)

Here are the two aria-live sections, and when I added the display: none property to each of them, the dual scroll bars disappeared, no other change was required for it. 

Their opacities are lowered and they are reduced down to 1px, however since they are positioned absolutely they are still treated as valid elements within the topmost container on the screen, hence they expand it.

**Comment by TorsteinHonsi** [comment]
Thanks! @oysteinmoseng can you check this out?

**Comment by naksenzh** [comment]
Hi @oysteinmoseng , please inform when you have any updates.

**Comment by oysteinmoseng** [comment]
Hi @naksenzh, this seems to be caused by the absolute positioning of these elements without an explicit relative parent. Try [this workaround](https://jsfiddle.net/ue57jgw8/) and let me know if it solves the issue - if so we will implement it in the core.

**Comment by umkoksal** [comment]
Hi @oysteinmoseng, I have tried the workaround provided and can confirm that it does resolve our issue. Thanks a lot for your time and assistance.

**Comment by oysteinmoseng** [comment]
I don't think this can be closed - still requires Torstein's workaround - reopening until further notice.

**Comment by raf18seb** [comment]
Correct me if this is not related, then I will create a new, separate ticket.
A similar issue is visible in IE - it works fine in **v5.0.10**, but has been failing since **v5.0.11** (I found a ticket in the changelog, probably  regression or related to the commit from here https://github.com/highcharts/highcharts/issues/6617)

It works fine in Chrome but fails in IE11.
**Steps to reproduce**: hide container, render the chart, show container, and then try to hide it again.
Due to the fact that jsFiddle is not supported in IE, I attach a small `index.html` demo:
```html
<html>

<head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Test Highcharts defect</title>

    <script src="https://code.highcharts.com/5.0.11/highcharts.js"></script>

    <style>
        #app-container,
        #view-container {
            padding: 10px;
            background-color: beige;
            border: 1px solid #000;
        }
    </style>

</head>

<body>
    <div id="app-container">
        <span>App container</span>
        <hr />
        <button id="hideContainerBtn">Hide container</button>
        <button id="renderChartBtn">Render chart</button>
        <button id="showContainersBtn">Show container</button>
        <hr />
        <div id="view-container">
            <span>View container</span>
            <hr />
            <div id="chart"></div>
        </div>

        <script>
            var viewContainer = document.getElementById('view-container'),
                hideContainerBtn = document.getElementById('hideContainerBtn'),
                showContainersBtn = document.getElementById('showContainersBtn'),
                renderChartBtn = document.getElementById('renderChartBtn');

            hideContainerBtn.addEventListener('click', function () {
                viewContainer.style.display = 'none';
            });

            renderChartBtn.addEventListener('click', function () {
                Highcharts.chart('chart', {
                    series: [{
                        data: [2, 5, 3, 4]
                    }]
                });
            });

            showContainersBtn.addEventListener('click', function () {
                viewContainer.style.display = 'block';
            });
        </script>

</body>

</html>
```

**Comment by raf18seb** [comment]
Correct me if this is not related, then I will create a new, separate ticket.
A similar issue is visible in IE - it works fine in **v5.0.10**, but has been failing since **v5.0.11** (I found a ticket in the changelog, probably regression or related to the commit from here #6617)

It works fine in Chrome but fails in IE11.

**Steps to reproduce**: hide both containers, render the chart, show both containers, and then try to hide it again.
Due to the fact that jsFiddle is not supported in IE, I attach a small `index.html` demo:
```html
<html>

<head>

    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <title>Test Highcharts defect</title>
    <script src="https://code.highcharts.com/highcharts.js"></script>

    <style>
        #app-container,
        #view-container {
            padding: 10px;
            background-color: beige;
            border: 1px solid #000;
        }
    </style>

</head>

<body>
    <div id="app-container">
        <span>App container</span>
        <hr />
        <button id="hideBothContainerBtn">Hide both containers</button>
        <button id="renderChartBtn">Render chart</button>
        <button id="showContainersBtn">Show both containers</button>
        <button id="hideViewContainerBtn">Hide only View container - isn't working</button>
        <hr />
        <div id="tab-container">
            <span>Tab container</span>
            <hr />
            <div id="view-container">
                <span>View container</span>
                <hr />
                <div id="container"></div>
            </div>
        </div>
    </div>

    <script>
        var tabContainer = document.getElementById('tab-container'),
            viewContainer = document.getElementById('view-container'),
            hideBothContainerBtn = document.getElementById('hideBothContainerBtn'),
            hideViewContainerBtn = document.getElementById('hideViewContainerBtn'),
            showContainersBtn = document.getElementById('showContainersBtn'),
            renderChartBtn = document.getElementById('renderChartBtn');

        hideBothContainerBtn.addEventListener('click', function () {
            tabContainer.style.display = 'none';
            viewContainer.style.display = 'none';
        });

        renderChartBtn.addEventListener('click', function () {
            Highcharts.chart('container', {
                series: [{
                    data: [2, 5, 3, 4]
                }]
            });
        });

        showContainersBtn.addEventListener('click', function () {
            tabContainer.style.display = 'block';
            viewContainer.style.display = 'block';
        });

        hideViewContainerBtn.addEventListener('click', function () {
            viewContainer.style.display = 'none';
        });
    </script>
</body>

</html>
```

**Comment by umkoksal** [comment]
@raf18seb I believe these are unrelated issues, our problem was primarily caused by a defect regarding positioning attribute in the accessibility module, as I see from your demo that the accessibility module is not included in your document

**Comment by naksenzh** [comment]
Closing as the mitigation provided worked or us
