### ISSUE TITLE
Mobile: Auto-highlighting first point with accessibility module

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#14278]
#### Expected behaviour
No auto-highlighting first point after focusing chart.

#### Actual behaviour
First point is highlighted (border + tooltip) even when it shouldn't.

Origin of the issue: https://github.com/highcharts/highcharts-ios/issues/341

Since it happens in the native app + webview, it's a bit hard to debug/recreate the issue. Some screencaps:

- iOS v12, multiple charts:
![onfocus-ios-12](https://user-images.githubusercontent.com/1453926/94544276-53ffae00-024b-11eb-9754-bc64ff1a26e8.gif)
- iOS v13, view change:
![onfocus](https://user-images.githubusercontent.com/1453926/94544287-58c46200-024b-11eb-8beb-fae861e310e2.gif)

#### Live demo with steps to reproduce
https://jsfiddle.net/BlackLabel/zagLyw50/27/show

Steps:
- open demo on a mobile device (with touch support)
- long tap above columns, e.g. here:
![Screen Shot 2020-09-28 at 17 30 27](https://user-images.githubusercontent.com/1453926/94542039-9b386f80-0248-11eb-91eb-32bfce468fcb.png)

Additionally: (reproduced on iOS) Open demo, leave Safari for some time (inactive app), go back to Safari. Safari (?) will focus chart back, highlighting the first point.

Note: Sometimes, instead of the bug, we get text highlighted on the chart. I don't know why.

#### Product version
v8.0.1+ 

#### Affected browser(s)
Latest Chrome (Android), Safari (tested iOS 12 and 13)

FYI @oysteinmoseng

**Comment by oysteinmoseng** [comment]
My guess is that this is triggered by the keyboard navigation, as it auto inits when the element is focused. We should be able to detect when this happens due to user touch, and avoid.

**Comment by alokdesai-cuelogic** [comment]
Are these fixed changes released on latest version.

**Comment by oysteinmoseng** [comment]
@alokdesai-cuelogic This should be fixed in the new release being released today or tomorrow.

**Comment by alokdesai-cuelogic** [comment]
I am still facing the same issue in latest version released v8.2.2

**Comment by oysteinmoseng** [comment]
@alokdesai-cuelogic I am not able to reproduce the issue on Android with Chrome. What device and browser are you using? Does the issue occur with the chart in the following link: https://jsfiddle.net/6hy857m9/show ?

**Comment by alokdesai-cuelogic** [comment]
@oysteinmoseng I am using the iPhone 11 device with iOS 14 installed. 
Steps to reproduce the issue on you demo iOS application is,

1. Open bar chart or line chart and select the third point from chart.
2. Change the tab and again come back to chart you have opened.

Observe that the first point in the chart is selected with rectangle around it.

**Comment by oysteinmoseng** [comment]
@pawelfus Are you able to reproduce this? Can we verify that the demo app is updated to latest?

**Comment by alokdesai-cuelogic** [comment]
@pawelfus Yes I am able to reproduce it on latest 8.2.2 demo app. I have attached the video of how to reproduce it.

[Screen Recording 2020-12-04 at 8.17.56 PM.mov.zip](https://github.com/highcharts/highcharts/files/5643427/Screen.Recording.2020-12-04.at.8.17.56.PM.mov.zip)

**Comment by pawelfus** [comment]
Yes, we are still able to recreate the issue:

![acc](https://user-images.githubusercontent.com/1453926/101344570-f8265680-3885-11eb-8d4c-fc27a8149278.gif)

Perhaps the demo in fiddle is now fixed, but this is something different? This only happens since iOS v13, so probably they have changed something. Maybe there's an additional `focus()` event fired by webview? We can work around this by disabling `accessibility` (tested).

**Comment by bre1470** [comment]
Issue exists also in Safari mobile. Basically it happens always, when the pointer event is not directly triggered on a point, and you refocus the view. In that case the original hoverPoint becomes invalid and the first gets set.
![Skjermopptak 2020-12-09 kl  10 38 30](https://user-images.githubusercontent.com/40056287/101613082-a0195c80-3a0b-11eb-95ae-3546886959f4.gif)

**Comment by bre1470** [comment]
It can be narrowed down to unhandled container clicks/touches. If you click on the legend it is fine after refocus, if you click near the legend the border issues occurs after refocus.

**Comment by oysteinmoseng** [comment]
This issue seems to have been fixed by Apple in latest iOS 14. Can anyone confirm that this is the case for the iOS app as well, not just web Safari?

**Comment by oysteinmoseng** [comment]
Closing due to no activity. Feel free to comment to reopen.
