### ISSUE TITLE
HighCharts not full screen when set height and weight in Options

### ISSUE THREAD

**Issue by CaptainHoangLe** [highcharts/highcharts#15421]
I have a chartOptions like that:
![image](https://user-images.githubusercontent.com/53038465/112929667-1240b900-9143-11eb-9f8b-a6f2e86d56e7.png)

"height" and "weight" are two param recieved from backend.
when i show in fullscreen of highcharts my chart will display below:
![image](https://user-images.githubusercontent.com/53038465/112930353-4e284e00-9144-11eb-90ef-c9f93d3de196.png)

However, when i remove props height and weight , it will be normal.
This Bug appear on all of type chart on my website
I can't reappear this bug on jsfiddle.
Please any one help me.
Thanks for all

#### Product version

        "highcharts": "^8.2.2",
        "highcharts-react-official": "^3.0.0",

**Comment by khlieng** [comment]
This got fixed in 9.0.1 (#15006).

8.2.2: https://jsfiddle.net/svpoeh5r/1/
Latest: https://jsfiddle.net/svpoeh5r/

**Comment by CaptainHoangLe** [comment]
> This got fixed in 9.0.1 (#15006).
> 
> 8.2.2: https://jsfiddle.net/svpoeh5r/1/
> Latest: https://jsfiddle.net/svpoeh5r/

wow ! I got it. Thank you very very much <3

**Comment by CaptainHoangLe** [comment]
> This got fixed in 9.0.1 (#15006).
> 
> 8.2.2: https://jsfiddle.net/svpoeh5r/1/
> Latest: https://jsfiddle.net/svpoeh5r/

Yikes ! It works in dev mode but when I run my project in product mode this bug is not fixed :(

**Comment by khlieng** [comment]
Hmm, I did a quick create-react-app production build and it works fine.

**Comment by CaptainHoangLe** [comment]
> Hmm, I did a quick create-react-app production build and it works fine.

In prod mode of my project , it work fine in some seconds but after that , my size 's chart will be changed to weight and height in chartOptions :(. I am using Highcharts to replace d3chart in apache superset

**Comment by KacperMadej** [comment]
Please recreate the problem and share the demo with the steps needed to recreate the problem with technical support - https://www.highcharts.com/blog/support/

Closing as already fixed.
