### ISSUE TITLE
Highmaps - Runtime exception - coordinates must be finite numbers

### ISSUE THREAD

**Issue by PeterMK85** [highcharts/highcharts#17192]
#### Expected behaviour
Does not produce a runtime exception

#### Actual behaviour
Runtime exception with the following error:
`coordinates must be finite numbers`

##### StackTrace:
```
TypeError
coordinates must be finite numbers

Call Stack
 checkCoord
  /node_modules/proj4/lib/checkSanity.js:11:11
 eval
  /node_modules/proj4/lib/checkSanity.js:3:3
 transform
  /node_modules/proj4/lib/transform.js:25:63
 transformer
  /node_modules/proj4/lib/core.js:26:69
 proj4
  /node_modules/proj4/lib/core.js:73:12
 e.b.transformToLatLon
  /node_modules/highcharts/highmaps.js:646:242
 d.projectedUnitsToLonLat
  /node_modules/highcharts/highmaps.js:677:420
 d.pixelsToLonLat
  /node_modules/highcharts/highmaps.js:681:25
 b.normalize
  /node_modules/highcharts/highmaps.js:627:329
 b.onContainerMouseLeave
  /node_modules/highcharts/highmaps.js:314:121
```

Coordinates verified: x/y is actually Null

##### Highcharts Only
https://stackblitz.com/edit/react-e52xux?file=index.js

##### With React Highcharts
https://stackblitz.com/edit/react-3tp3yi?file=index.js

##### Details
If you keep a single Highmap visualisation, it works, two or more, start to crash. 

1. Hover over eu
2. Hover over usa
3. Hover over eu

_Crash_

#### Product version
| dependency | version |
| --- | ---|
| [highcharts](https://www.npmjs.com/package/highcharts) |  10.0.0 |
| [proj4](https://www.npmjs.com/package/proj4) | 2.6.1 |
|  [highcharts-react-official](https://www.npmjs.com/package/highcharts-react-official)  |  3.0.0 _(also exists with 3.1.0)_  |
| [react](https://www.npmjs.com/package/react) | 16.14.0 |
| [react-dom](https://www.npmjs.com/package/react-dom) | 16.14.0 |

#### Affected browser(s)
All (Chrome & Mozilla verified)

**Comment by raf18seb** [comment]
Hi @PeterMK85, thanks for creating the ticket!

There must be something wrong with your map source because it's working fine with our official ones (no need to load proj4), see demo: https://stackblitz.com/edit/react-fw5mjk?file=index.js

**Comment by rjhoskins** [comment]
Any update/workaround here?  Having same issue w/ react demo [here](https://codesandbox.io/s/highcharts-react-simple-chart-forked-y2ffxc?file=/demo.jsx)

**Comment by hubertkozik** [comment]
This bug has been fixed. There are no errors while using code directly from the master branch.

**Demo:** https://jsfiddle.net/BlackLabel/k5o6qvgj/

Closing as completed.

**Comment by vintagefuture** [comment]
Hello,

I believe this bug is still present, I could reproduce on latest version of Highcharts (at the time of writing **11.4.8**) and of highcharts-react-official (**3.2.1**):

```
TypeError
coordinates must be finite numbers
checkCoord
https://d5jr3m.csb.app/node_modules/proj4/lib/checkSanity.js:15:11
$csb__default
https://d5jr3m.csb.app/node_modules/proj4/lib/checkSanity.js:6:13
transform
https://d5jr3m.csb.app/node_modules/proj4/lib/transform.js:24:27
transformer
https://d5jr3m.csb.app/node_modules/proj4/lib/core.js:31:33
proj4
https://d5jr3m.csb.app/node_modules/proj4/lib/core.js:76:12
$csb$eval/</</c.prototype.transformToLatLon
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:651:208
$csb$eval/</</u</e.prototype.projectedUnitsToLonLat
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:683:420
$csb$eval/</</u</e.prototype.pixelsToLonLat
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:687:52
normalize
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:630:390
$csb$eval/</</c</c.prototype.onContainerMouseLeave
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:313:127
$csb$eval/</</c</c.prototype.setHoverChartIndex
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:327:87
$csb$eval/</</c</c.prototype.onContainerMouseMove
https://d5jr3m.csb.app/node_modules/highcharts/highmaps.js:313:428
```

It's a bit tricky because it crashes only at **re-renders + the mouse passes over the map**. At initial load of the map the error does not occur.

Minimal sanbox to reproduce: https://codesandbox.io/p/sandbox/wispy-thunder-d5jr3m

Video of the issue: 

https://github.com/user-attachments/assets/22fff57f-c565-47e2-b793-6c2ce3c1008a





Could this be looked at again?

Thanks in advance!

**Comment by hubertkozik** [comment]
You are right @PeterMK85. This problem is again with us since Highcharts v11.4.4, it was working correctly in Highcharts v11.4.3. I can reproduce even in this vanilla JS demo: https://jsfiddle.net/BlackLabel/k5o6qvgj/

_Internal note_
Bisected to 666f69897d382d7fdd161f51e9273c17e7445554.

**Comment by TorsteinHonsi** [comment]
@PeterMK85 The issue is fixed in the master now. However, please note that the use of Proj4 is no longer required since projection is built into Highcharts Maps. Instead you can load the leaner TopoJSON maps and apply projection from the [mapView options](https://api.highcharts.com/highmaps/mapView.projection) set.

**Comment by ibeqiri-flexera** [comment]
@TorsteinHonsi how you planned to support the cases where x/y coordinates were used to show mapBubble series on the mapChart? After upgrading to v11, none of these coordinates are working as seems like internal projection is breaking it. 

We still use the old pre-projected world.geo.json data that you provide. 

Was this move of projection logic to the client done with backward compatibility in mind? At least, is there a way to disable this client-side projection so it does not interfere with x/y coordinates there are using throughout our web apps.

**Comment by TorsteinHonsi** [comment]
> Was this move of projection logic to the client done with backward compatibility in mind?

Yes, we still support the old pre-projected geoJSON files, as can be seen in two of our demos: 
* https://www.highcharts.com/demo/maps/geojson
* https://www.highcharts.com/demo/maps/mapline-mappoint

> none of these coordinates are working as seems like internal projection is breaking it

Can you show us how it is set up?

**Comment by ibeqiri-flexera** [comment]
> > Was this move of projection logic to the client done with backward compatibility in mind?
> 
> Yes, we still support the old pre-projected geoJSON files, as can be seen in two of our demos:
> 
> * https://www.highcharts.com/demo/maps/geojson
> * https://www.highcharts.com/demo/maps/mapline-mappoint
> 
> > none of these coordinates are working as seems like internal projection is breaking it
> 
> Can you show us how it is set up?

A sample of our data from storybook:
```
const series = [ {
        name:   'Aes',
        type:   'mapbubble',
        joinBy: ['hc-middle-x', 'x'],
        marker: {
            fillOpacity: 0.2,
            lineWidth:   2,
        },
        data: [
            {
                region:      'us-west-2',
                code:        'US',
                x:           600,
                y:           -7900,
                z:           91,
                tooltipData: {
                    byState: {
                        running: 91,
                        stopped: 0,
                    },
                    totalCount: 91,
                },
            },
           {
            name:                'Countries',
            mapData:             worldMap,
           borderWidth:         1,
           enableMouseTracking: false,
           showInLegend:        false,
           nullColor:           'rgba(184, 195, 207, 0.4)',
          borderColor:         'rgba(184, 195, 207, 0)',
      },
]

// chart options
this.chartOptions = {
            chart: {
                borderWidth:     0,
                backgroundColor: '#ffffff',
                height:          this.height,
                map:             worldMap,
                proj4:           proj4,
            },
            credits:       {enabled: false},
            rangeSelector: {enabled: false},
            navigator:     {enabled: false},
            scrollbar:     {enabled: false},
            exporting:     {enabled: false},
            ....
            colors: this.colors,
            series: this.series
        };

// template
 <highcharts-chart
          constructorType="mapChart"
          [Highcharts]="Highcharts"
          [options]="chartOptions"
          [(update)]="isUpdate"
          (chartInstance)="onChartInstanceCreation($event)">
      </highcharts-chart>
```
