### ISSUE TITLE
When reset zoom button the colors on line will revert back to legend color

### ISSUE THREAD

**Issue by JunaydIqbal** [highcharts/highcharts#17945]
#### Expected behaviour
When applying colorKey on the chart, the line colors changed when resetting the zoom. The color changed to the same as the legend color of the line. The issue I posted on highcharts forums so someone replied to me that there is no issue on my side but this issue is on highcharts.

#### Actual behaviour
I want to remain the same colors when reset zoom the chart. I have also attached a gif of my issue.

#### Live demo with steps to reproduce
Check it on my fiddle: https://jsfiddle.net/wz9sn31b/2/
Issue reported on forums: https://www.highcharts.com/forum/viewtopic.php?f=12&t=49776

#### Product version

HIghstock

#### Affected browser(s)
All

#### Issue shown on attached gif file:
![Recording 2022-11-03 at 15 46 05](https://user-images.githubusercontent.com/85728756/200248073-192dc089-b9ef-477a-a7dc-fb4f0d0909a8.gif)

gif link if not loaded: https://media.giphy.com/media/gg5Kx2hx3xTBaxZZR3/giphy.gif

**Comment by robertalexa** [comment]
I was experiencing the exact behaviour with area charts. However this seems to have been fixed in v11.4.0

OP, not sure if you are event using this anymore, but maybe it helps you in some way.

**Comment by karolkolodziej** [comment]
Hi @robertalexa! 

Thank you for the additional input. 
As far as I see the issue is still visible with the line series.

**Comment by jszuminski** [comment]
As a **workaround**, you could add this to your demo:

```
(function(H) {
  H.addEvent(H.Series, 'afterTranslate', function() {
    if (
      this.chart.colorAxis &&
      this.chart.colorAxis.length ||
      this.colorAttribs
    ) {
      this.oldData = this.data;
      this.data = this.points;
    }
  }, { order: 0 });

  H.addEvent(H.Series, 'afterTranslate', function() {
    if (
      this.chart.colorAxis &&
      this.chart.colorAxis.length ||
      this.colorAttribs
    ) {
      this.data = this.oldData;
      delete this.oldData;
    }
  }, { order: 2 });
}(Highcharts));
```

Demo with a workaround: https://jsfiddle.net/BlackLabel/vbwhLgz9/

---
_Internal note:_
The `seriesTranslateColors` method should iterate over `this.points`, not `this.data`:
https://github.com/highcharts/highcharts/blob/f31c8cd641a09cc93e36b6eaa9824490fa9243af/ts/Core/Axis/Color/ColorAxisComposition.ts#L345-L358

**Comment by pawelfus** [comment]
*Internal note:*
Reuse `Series.getPointsCollection()`
