### ISSUE TITLE
Treemap graph not working with new version

### ISSUE THREAD

**Issue by danielchirinos** [highcharts/highcharts#18889]
hello,
treemap graphics or treemap types have stopped working even on your website in demo view.

this happened today since highcharts.js was updated to the latest version.

any suggestions?

thank you!

![image](https://user-images.githubusercontent.com/26119261/234688130-9aa0dce1-ce4a-4251-9b84-8311d3881bbe.png)
![image](https://user-images.githubusercontent.com/26119261/234688266-1b1bee72-d097-4ffd-93cc-ad75693d56cc.png)

**Comment by TorsteinHonsi** [comment]
Thanks for reporting! This is a cache issue, apparently the old `highcharts.js` file was cached in your browser, while the `accessibility.js` file was not. This should fix itself, if not you can try a hard refresh.

<img width="788" alt="Skjermbilde 2023-04-27 kl  08 06 52" src="https://user-images.githubusercontent.com/227836/234774191-e0bb200b-7234-4836-af68-cfe7b9f204e1.png">

**Comment by danielchirinos** [comment]
hi @TorsteinHonsi , It doesn't seem like a cache issue, since I've opened the demos from the highchart page directly in different browsers and they still don't work. I already did the hard reset of all the dependencies and this type of graphics continues the same

this examples demo in you web site dont showing:

https://www.highcharts.com/demo/treemap-coloraxis
https://www.highcharts.com/demo/variable-radius-pie

thanks

**Comment by TorsteinHonsi** [comment]
Could it be the CloudFlare cache? How is it looking from your location, @raf18seb ?

@danielchirinos The version header of https://code.highcharts.com/highcharts.js should be 11.0.0. I assume it is 10.3.3 from where you are.

**Comment by danielchirinos** [comment]
@TorsteinHonsi Yes, that's right, how can I change to 11? the code.higchart link points directly to 10.3.3

**Comment by raf18seb** [comment]
Both demos work for me on the website, in jsFiddle, codepen, in Chrome, Firefox, Sarafi, Edge (on Mac)

<img width="1502" alt="image" src="https://user-images.githubusercontent.com/23310742/234920968-af42fd44-0180-4bc1-893a-4915b352334e.png">

**Comment by danielchirinos** [comment]
@TorsteinHonsi  since code.highchart still points to 10.3.3 I decided to download version 11 in zip and directly integrate the dependencies. With this I was able to correct the problem.

thank you!

**Comment by TorsteinHonsi** [comment]
> Yes, that's right, how can I change to 11? the code.higchart link points directly to 10.3.3

@danielchirinos You can add the version number after the domain name:

https://code.highcharts.com/11/highcharts.js

That also applies to the module files. But this should sort itself out once the cache expires.
