### ISSUE TITLE
Issues related to zoom Reset button, export icon, and title

### ISSUE THREAD

**Issue by kdavidenkovmware** [highcharts/highcharts#19908]
#### Expected behaviour
- The zoom button obeys `align` property 
- The zoom button and export icon stack appropriately, even without a title.

#### Actual behaviour
- Zoom reset button ignores any text in `align` property.
- zoom reset button shifts over the export icon when there is no title

#### Live demo with steps to reproduce
https://jsfiddle.net/kdavidenkovmware/5zygms3h/6/
Steps to Reproduce: 
- Demo should already be set up to display error. Just zoom in.

#### Product version
Highcharts 10.3.3 and 11.1.0

#### Affected browser(s)
Chrome Version 117.0.5938.92 (Official Build) (x86_64)

**Comment by karolkolodziej** [comment]
Hi @kdavidenkovmware! 

It is already fixed on the `master` branch and will be released in the upcoming version.
Could you please take a look and the demo and confirm if that is what you have been looking for- [demo](https://jsfiddle.net/BlackLabel/pvdg650L/)?

**Comment by kdavidenkovmware** [comment]
@karolkolodziej With that demo you linked, issue of align not working is resolved. But if I switch the `align` to right, I can still see issue 2, but if I can align the button, that takes care of my immediate issue. Thanks!

**Comment by karolkolodziej** [comment]
You are right! 
For now, we don't have any collision detection for the zoom button but you can easily fix this by setting `y` for the button position- [demo](https://jsfiddle.net/BlackLabel/fm6qo89v/).

We can treat it as an enhancement 😉

**Comment by kdavidenkovmware** [comment]
I'll give that a try, thanks @karolkolodziej
