### ISSUE TITLE
ES5 build not working - inlcudes-function polyfill too late in the file and dissolve-function does not exist

### ISSUE THREAD

**Issue by sjoris** [highcharts/highcharts#20939]
#### Expected behaviour
For Highcharts to work in legacy browsers, using the ES5-build.
According to:
https://www.highcharts.com/docs/getting-started/system-requirements#supporting-ie-11-and-other-legacy-browsers

#### Actual behaviour
- Firefox: Highcharts crashes, so no chart is visible. The _dissolve_-function does not exist on the Pointer-object.
- PhantomJS: Charts are visible, but datalabels are missing. The polyfill for the _includes_-function is created at the end, but should be created earlier, because it is used by more components. The first error is:
_TypeError: undefined is not a constructor (evaluating 'SVGElementClass.symbolCustomAttribs.includes('borderRadius')')_

#### Live demo with steps to reproduce
https://jsfiddle.net/71v95rbe/2/ (Must be viewed in Firefox. I can't create a live demo for PhantomJS)

In my own environment I moved the following polyfills to the beginning of the file, **right before** the declaration of the __registerModule_-function:

- Array.prototype.includes
- Object.entries
- Object.values

And I removed the call:
_G.Pointer.dissolve();_

#### Product version
Highcharts 11.4.0

#### Affected browser(s)
PhantomJS 2.1.1 and Firefox 124.0.1

**Comment by hubertkozik** [comment]
Hi @sjoris! You're right, es5 build is not working for Highcharts v11.4.0. However, this issue is already fixed on the master branch by these Pull Requests: https://github.com/highcharts/highcharts/pull/20774 https://github.com/highcharts/highcharts/pull/20812

The fix will be applied to the next release of Highcharts. Closing this issue as completed.

**Comment by sjoris** [comment]
Hi @hubertkozik,
Thank you for your reply, but i still see the _dissolve_-function in the master branch (ts/masters-es5/highcharts.src.ts, line 22).
Doesn't that have to be:
`G.Pointer.destroy();`
Because the Pointer object does not have an _dissolve_-function: ts/Core/Pointer.ts
Or am I missing something?
