### ISSUE TITLE
Uneven space between columns

### ISSUE THREAD

**Issue by graineri** [highcharts/highcharts#2690]
When drawing a large number of columns, it seems they are not evenly spaced.

Example:
http://jsfiddle.net/C4HT9/1/
(It might be necessary to zoom in or add more columns, depending on the monitor's resolution)

If I take a look at the rect tags I see that the x value does not have a fixed interval.
Example:
rect fill="#2f7ed8" x="5.5" ...
rect fill="#2f7ed8" x="8.5" ...
rect fill="#2f7ed8" x="11.5" ...
rect fill="#2f7ed8" x="15.5" ...
rect fill="#2f7ed8" x="18.5" ...
rect fill="#2f7ed8" x="21.5" ...
rect fill="#2f7ed8" x="25.5" ...

**Comment by ncoquelet** [comment]
Same problem with my chart
There is no solution to resolved it ?

I add two demos where it's really ugly ...

One with group : http://jsfiddle.net/cxLojhfm/embedded/result/
One with a mini chart : http://jsfiddle.net/7u7L33hc/

**Comment by KacperMadej** [comment]
Resolved through [`crisp`](https://api.highcharts.com/highcharts/series.column.crisp) option.
Demo: http://jsfiddle.net/BlackLabel/7u7L33hc/19/

**Comment by Izothep** [comment]
It looks that the issue is still visible in some specific use cases even with `crisp` option, when pointPadding is manually added.

Live example:
https://jsfiddle.net/izothep/6wnr4xh3/2/

**Comment by KacperMadej** [comment]
This might be limitations of sub-pixel precision of SVG rendering in a browser. `shape-rendering="optimizeSpeed"` seems to be fixing it for me (Chrome/Win7). Demo: https://jsfiddle.net/BlackLabel/8kqauvL6/
On the other hand, without the `crisp: false` columns are rendered without the issue - https://jsfiddle.net/BlackLabel/8kqauvL6/1/
