### ISSUE TITLE
addPoint() doesn't update a Stockchart correctly when navigator is disabled

### ISSUE THREAD

**Issue by thombergs** [highcharts/highcharts#3452]
I tried to create a Stockchart that is updated dynamically by calling addPoint(). All works fine, as long as the navigator is enabled. If I disable the navigator, however, new points are not added to the series (at least the chart does not visually update correctly).

See http://jsfiddle.net/gc85y2ea/ for example, which is one of the demo examples with disabled navigator.

**Comment by sebastianbochan** [comment]
+1

**Comment by TorsteinHonsi** [comment]
I have fixed this on the branch for the related #2266 : http://jsfiddle.net/highcharts/gc85y2ea/1/

Will make sure it is tested when merging.

**Comment by Jonno** [comment]
This bug still exists if the scrollbar is disabled
` scrollbar: {
                enabled: false
        },
        navigator: {
                enabled: false
        }`

**Comment by pawelfus** [comment]
Thank you for reporting! Let me reopen the ticket.

**Workaround:**
Manually set extremes after adding a point: http://jsfiddle.net/gc85y2ea/3/
