### ISSUE TITLE
Halo visible outside plotting area

### ISSUE THREAD

**Issue by pawelfus** [highcharts/highcharts#3916]
Example: http://jsfiddle.net/yaot3ebq/

Steps:

- zoom-in, that some of the points are outside the plotting area
- hover one of visible points
- move mouse to hover points outside the plotting area: tooltip and halo are displayed

![helo](https://cloud.githubusercontent.com/assets/1453926/6441026/b6855476-c0e3-11e4-843d-a66bd4e14376.png)

**Comment by highslide-software** [comment]
Simplified non-Highstock demo: http://jsfiddle.net/highcharts/9vxtf5nq/. Hover on left side of plot area, tooltip displays for the first point.

**Comment by pawelfus** [comment]
Another case, it doesn't have to be  outside the plotting area, just misplaced: http://jsfiddle.net/n6buh1o6/3/

Steps:

- hover one of the points
- zoom in
- we get tooltip for proper point, but halo is misplaced

**Comment by sebastianbochan** [comment]
Seems that problem also exists in bubble chart.

Steps:
1) http://www.highcharts.com/demo/bubble
2) hover on gray point
3) zoom in 
4) halo is misplaced

https://drive.google.com/file/d/0ByEiCW-yZo19S1ZDOGlVWjllSkU/view

Browser: Chrome 45.0.2454.85

**Comment by mekhatria** [comment]
+1

Same issue:

Example: http://jsfiddle.net/6n2ja5t3/
Forum:     http://forum.highcharts.com/highcharts-usage/markers-showing-outside-of-plot-area-when-zoomed-in-t34899/

**Comment by sebastianbochan** [comment]
+1

**Comment by scottpdawson** [comment]
I have this problem, too. I traced the change in the highCharts library to code that was introduced in  4.1.6 (2015-06-12) of highcharts-more.js. I did trace a change to line 9575 of this file that, when reverted to 4.1.5, results in the issue going away.

```
// 4.1.5 CODE - tooltips only appear for visible points //

if (p && defined(p.plotX) && defined(p.plotY)) {
	if ((p.dist.distX < distance) || ((p.dist.distX === distance || p.series.kdDimensions > 1) && p.dist.distR < rdistance)) {
		distance = p.dist.distX;
		rdistance = p.dist.distR;
	}
}

// 4.1.6 CODE - tooltip outside of visible range //

if (p && typeof p.dist === 'number' && p.dist < distance) {
	distance = p.dist;
	kdpoint = p;
}

```

**Comment by TorsteinHonsi** [comment]
It's like #5085 (fixed in dev branch), except this is on the Y axis.

**Comment by scottpdawson** [comment]
Do you know when this fix will be released?

**Comment by TorsteinHonsi** [comment]
It was fixed with version 4.2.4, see http://jsfiddle.net/highcharts/9vxtf5nq/

**Comment by dotnetjalps** [comment]
This is still happening in highcharts 5 also. When you zoom to x its going outside.

![bug](https://cloud.githubusercontent.com/assets/5141580/19798635/ea306bb2-9d0f-11e6-894a-69ea46abc2ac.png). 

You should have reopened this issue. I am using highchart 5.0 version.

**Comment by TorsteinHonsi** [comment]
Live demo please? With [our latest demo](http://jsfiddle.net/highcharts/9vxtf5nq/) it doen't happen.

**Comment by dotnetjalps** [comment]
I will create a JSfiddle for that.
