### ISSUE TITLE
Shared tooltip makes 'click' event of Points always target a single point in the set of shared points.

### ISSUE THREAD

**Issue by smithk58** [highcharts/highcharts#3919]
JSFiddle: http://jsfiddle.net/d724xgdy/2/

If you turn on shared for tooltips your point click events won't take affect on the exact point you click. 

In the above JS fiddle you can see that even if you click one of the top points it will trigger the point click event for the bottom point instead. If you add more series it will still always trigger the click event for the bottom point.

**Comment by highslide-software** [comment]
No matter what point we click, the event is triggered on Series 2: http://jsfiddle.net/highcharts/d724xgdy/3/

Did not happen in HIghcharts 4.0.

**Comment by KacperMadej** [comment]
Broken again. Was working until 4.1.10 (working with 4.1.9 - http://jsfiddle.net/re30zs3p/)

**Comment by TorsteinHonsi** [comment]
Fails since 4392d1c

New reproduction steps:
1. Open http://jsfiddle.net/highcharts/d724xgdy/7/
2. Click any point in _Series 2_, and note that the console prints _Series 1_.

**Comment by TorsteinHonsi** [comment]
Fixed with 0ca4f6aadc222b, reverting previous fix.

**Comment by Drumstix42** [comment]
This issue is still occurring again. It seems whichever point you mouse gets closest to first, is the one that outputs in the console. http://jsfiddle.net/highcharts/d724xgdy/7/

**Comment by pawelfus** [comment]
Thanks for reporting @Drumstix42 
It works fine with out dev-branch which should be merged before releasing 5.0.8, demo: http://jsfiddle.net/d724xgdy/19/

Heads-up @jon-a-nygaard and @TorsteinHonsi

**Comment by jon-a-nygaard** [comment]
Thanks for the heads up @Drumstix42 and @pawelfus . I would just like to confirm that this issue is fixed again in 5.0.8 and above.
