### ISSUE TITLE
Donut charts export: data-labels superimposed by connectors  

### ISSUE THREAD

**Issue by ValentinH** [highcharts/highcharts#3948]
I have noticed in several cases that when exported (PNG or PDF), the data-labels placed on the left side of the pie/donut are too close from their connectors and sometimes their connectors are drawn over them...

Example with the 'other browsers' label: http://jsfiddle.net/m0ofqdco/

**Comment by pawelfus** [comment]
Do you refer this duplicated labels? See image below: 
![chart 36](https://cloud.githubusercontent.com/assets/1453926/9439171/e327c850-4a64-11e5-8910-04defb98f51f.png)

This is reported here: #3649

If this is not the issue, then it looks like fixed ( "Other Browsers 0.7%" doesn't collide with the connector). Could you confirm?

**Comment by ValentinH** [comment]
Nope I mean this problem: The pink connector  of "Other browsers" is placed under the label (under the 0.7 exactly). 

Example.
![chart 4](https://cloud.githubusercontent.com/assets/2678610/9439920/90bcf476-4a6b-11e5-82da-1a2aecfde827.png)

I have set `text-shadow: 'none'` to hide the duplicated label problem: http://jsfiddle.net/m0ofqdco/1/

**Comment by pawelfus** [comment]
Any specific browser? Testes with latest chrome: 
![chart 39](https://cloud.githubusercontent.com/assets/1453926/9440019/3bbd92d6-4a6c-11e5-87b0-33c5fde88986.png)

**Comment by ValentinH** [comment]
I am using Chrome on Linux, but are you talking about PNG image export?

**Comment by pawelfus** [comment]
I mean both, PNG and PDF, which looks the same - as in the image (it's directly exported image).

**Comment by ValentinH** [comment]
So this means that the browser has an influence on the generated image?

**Comment by ValentinH** [comment]
Here's what I get on Firefox/Linux 40.0: 
![chart](https://cloud.githubusercontent.com/assets/2678610/9441274/52da0a36-4a75-11e5-9c98-d3a3a78abbd1.png)

**Comment by highslide-software** [comment]
@ValentinH Your fiddle has a chart with variable width, which means we can't trust the issue to be reproduced. Can you share a fiddle with a fixed pixel width?

**Comment by ValentinH** [comment]
Sure: http://jsfiddle.net/m0ofqdco/3/ (still the same problem with the fixed width btw)

**Comment by gvaartjes** [comment]
Probably fixed by updating the export server with phantomjs version 2.

@ValentinH Could you confirm this?

**Comment by ValentinH** [comment]
When using http://export.highcharts.com/, still the same issue, but I don't know if it runs phantomjs 2...
