### ISSUE TITLE
Wrong scaling of HTML content in exported charts when exporting.allowHTML = true

### ISSUE THREAD

**Issue by rja71** [highcharts/highcharts#4648]
Since the new Highcharts version 4.1.9, when a chart uses HTML in Y axis labels : 
     yAxis.labels.useHTML:true
and when HTML is allowed in exports : 
     exporting.allowHTML:true
the Y axis labels are not displayed correctly.

Here is a demo with this issue : 
http://jsfiddle.net/xLsmucv8/

Thank you,

rja71

**Comment by highslide-software** [comment]
The problem is with scaling of `foreignObject` in PhantomJS 2. It worked correctly with PhantomJS 1.x, that we were running until October 2015. 

With PhantomJS 2, the SVG scales correctly by `page.zoomFactor`, but the HTML inside `foreignObject` does not. 

For the records, please note that the `allowHTML` option is marked Experimental.

**Comment by highslide-software** [comment]
Apparently we can work around the issue by wrapping the HTML in a div with a scale transform. Here's a drop-in fix:
```js
    // Drop-in workaround for #4648
    (function (H) {
        H.wrap(H.Chart.prototype, 'sanitizeSVG', function (proceed, svg) {
            svg = svg.replace(
                    '<body xmlns="http://www.w3.org/1999/xhtml">',
                    '<body xmlns="http://www.w3.org/1999/xhtml">' +
		                '<div style="-webkit-transform: scale(2, 2); -webkit-transform-origin: 0 0 !important">'
                ).replace(
                	'</body>',
                	'</div></body>'
                );
            return proceed.call(this, svg);
        });
    }(Highcharts));
```
[View it live on jsFiddle](http://jsfiddle.net/highcharts/xLsmucv8/1/).

@oysteinmoseng The real fix should be to do this replacement conditionally in the PhantomJS script, since the issue is with PhantomJS.

**Comment by gvaartjes** [comment]
Cool, I guess @oysteinmoseng didn't try this.

**Comment by oysteinmoseng** [comment]
Wow, nice, did not think to try that.

**Comment by oysteinmoseng** [comment]
Fixed in new highcharts-exporting-server repo in commit highcharts/highcharts-export-server@2b7c2d72d8c26f17fb2464e6e446234383779de3

**Comment by TorsteinHonsi** [comment]
This is still an issue with the online exporting server. What's the status?

**Comment by TorsteinHonsi** [comment]
@oysteinmoseng @gvaartjes

**Comment by TorsteinHonsi** [comment]
This is now released in the online export server.
