### ISSUE TITLE
each is not defined

### ISSUE THREAD

**Issue by tquetano-r7** [highcharts/highcharts#4842]
Just updated to 2.1.10 and am receiving an "each is not defined" error at the folling code:

```
// create the circlepin and squarepin icons with anchor
    each(['circle', 'square'], function (shape) {
        symbols[shape + 'pin'] = function (x, y, w, h, options) {

            var anchorX = options && options.anchorX,
                anchorY = options &&  options.anchorY,
                path,
                labelTopOrBottomY;

            // For single-letter flags, make sure circular flags are not taller than their width
            if (shape === 'circle' && h > w) {
                x -= mathRound((h - w) / 2);
                w = h;
            }

            path = symbols[shape](x, y, w, h);

            if (anchorX && anchorY) {
                // if the label is below the anchor, draw the connecting line from the top edge of the label
                // otherwise start drawing from the bottom edge
                labelTopOrBottomY = (y > anchorY) ? y : y + h;
                path.push('M', anchorX, labelTopOrBottomY, 'L', anchorX, anchorY);
            }

            return path;
        };
    });
```

**Comment by pawelfus** [comment]
Do you have jsFiddle demo? Or is it the same issue as in #4818 (webpack issue) ?

**Comment by tquetano-r7** [comment]
While I am also using webpack, I have never gotten a highcharts is undefined error, so I'm not entirely sure its related to that issue ... it just says the above each function that is attempting to be run doesn't exist. That said, I'll wait until that issue is resolved before pursuing this further.

**Comment by pawelfus** [comment]
I mean [this comment](https://github.com/highcharts/highcharts/issues/4818#issuecomment-163866364). This bug is present only in 4.1.10 version.

**Comment by tquetano-r7** [comment]
Ah gotchya. No worries.

**Comment by TorsteinHonsi** [comment]
Fixed with Highcharts 4.2

**Comment by tquetano-r7** [comment]
I don't get this error anymore, but I'm using highstock-release and get the "Highcharts is undefined" error now. I even installed highcharts in case it was an undeclared peer dependency, still get the same error.

**Comment by TorsteinHonsi** [comment]
Did you install according to the [updated docs for Highcharts 4.2](http://www.highcharts.com/docs/getting-started/install-from-npm)?

```js
var Highcharts = require('highcharts/lib/highstock');
// Load module after Highcharts is loaded
require('highcharts/lib/modules/exporting')(Highcharts);
// Create the chart
Highcharts.chart('container', { /*Highcharts options*/ });
```
Notice how the module is loaded, that may be where the error comes from. It takes Highcharts as an option.
