### ISSUE TITLE
colorAxis.labels: overflow and rotation

### ISSUE THREAD

**Issue by KacperMadej** [highcharts/highcharts#4985]
`colorAxis.labels.overflow` doesn't seems to work, while in [API](http://api.highcharts.com/highmaps#colorAxis.labels.overflow) is not deprecated.
Example: http://jsfiddle.net/t4rx2oz0/

Setting `rotation` for labels with value close to `0` or `360` causes ticks and colorAxis extremes to act strange.
Example: http://jsfiddle.net/t4rx2oz0/1/
Also, setting `rotation` to `360 * n` causes problems: http://jsfiddle.net/t4rx2oz0/2/

(The goal was to set `align: "center"` for all labels, even the ones on edges using options.)

**Comment by TorsteinHonsi** [comment]
Related to #3463 (see note there).

**Comment by KacperMadej** [comment]
Unable to recreate using version 6.1.4.

API is not updated. Below code:

https://github.com/highcharts/highcharts/blob/28cd32c5c/js/parts-map/ColorAxis.js#L332-#L342

should be more like this:

https://github.com/highcharts/highcharts/blob/28cd32c5c0db314006e3990db0e5bf6bf5ca3d1b/js/parts/Axis.js#L900-#L911

**Comment by sophiebremer** [comment]
See https://github.com/highcharts/highcharts/pull/9148 for a fix of colorAxis.labels.overflow

**Comment by bre1470** [comment]
@KacperMadej Can we close this issue? It looks like all things are fixed now.

**Comment by KacperMadej** [comment]
@bre1470 No, please don't close this yet. I will handle this.

The description is still not the same for `colorAxis.labels.overflow` and `xAxis.labels.overflow`
https://github.com/highcharts/highcharts/blob/cce6c790326c5ff108186e05f1e039ab8a4d4503/ts/parts-map/ColorAxis.ts#L515-L520

https://github.com/highcharts/highcharts/blob/cce6c790326c5ff108186e05f1e039ab8a4d4503/ts/parts/Axis.ts#L1594-L1599

This is an essential difference since API reference shows only that and nothing about the `@validvalue`

https://api.highcharts.com/highmaps/colorAxis.labels.overflow

**Comment by bre1470** [comment]
Ah, I see. 👍
