### ISSUE TITLE
Wrong script paths in "Install from Bower" example in documentation

### ISSUE THREAD

**Issue by stpoa** [highcharts/highcharts#6289]
#### Expected behaviour
After adding path to highcharts.js Highcharts variable should be in window object.

#### Actual behaviour
After adding path to highcharts.js Highcharts variable is not added to window object.

#### Live demo with steps to reproduce

Does not work on MacOS and Windows

    <html lang="en">

    <head>
      <meta charset="utf-8">
    </head>
      
    <body>
      <div id="chart"></div>
      <script src="/bower_components/highcharts/highcharts.js"></script>
      <script>
        const options = { series: [{data: [1,2,3,4,5]}] }
        Highcharts.chart('chart', options)
      </script>
    </body>

    </html>

When adding dot before path it works.

    <html lang="en">

    <head>
      <meta charset="utf-8">
    </head>
      
    <body>
      <div id="chart"></div>
      <script src="./bower_components/highcharts/highcharts.js"></script>
      <script>
        const options = { series: [{data: [1,2,3,4,5]}] }
        Highcharts.chart('chart', options)
      </script>
    </body>

    </html>

#### Affected browser(s)
Chrome, Firefox, Safari, IE

**Comment by TorsteinHonsi** [comment]
Fixed, thanks!

**Comment by stpoa** [comment]
Unfortunately, path on a page still isn't correct :(
It should not start with slash.

It looks like:
```<script src="/./bower_components/highcharts/highcharts.js"></script>```

It should look like:
```<script src="./bower_components/highcharts/highcharts.js"></script>```

**Comment by TorsteinHonsi** [comment]
That's strange, the article in the Joomla editor shows this correctly, both with the visual code editor and the text editor. 

@jon are you aware of any escaping by Joomla that influences this?

**Comment by jon-a-nygaard** [comment]
It is likely due to a TinyMCE's url conversion: https://www.tinymce.com/docs/demo/url-conversion/
Unfortunately we're not allowed to edit the neccessary settings in Joomla, so we might have to override the plugin.
