### ISSUE TITLE
Error in bar chart: <text> attribute x: Expected length, "NaN"

### ISSUE THREAD

**Issue by kaljak** [highcharts/highcharts#6324]
#### Expected behaviour
Chart should be rendered without any script errors.

#### Actual behaviour
If a bar chart is rendered and module "grid-axis" is loaded a script error occures (see jsfiddle):
Error: <text> attribute x: Expected length, "NaN" (highcharts.src.js:5356).

As far as I can see the problem is this line in grid-axis.src.js:143
`options.title = '';`

#### Live demo with steps to reproduce
Run:
https://jsfiddle.net/kaljak/5uudokuL/

#### Affected browser(s)
Chrome, Firefox, etc...

**Comment by kaljak** [comment]
fyi: The error already occures in released v5.0.7.

**Comment by larsac07** [comment]
Fixed in 29a9e3223 in gantt branch: http://github.highcharts.com/gantt/modules/grid-axis.src.js

**Comment by kaljak** [comment]
Hey @larsac07 

this issue still occures in v5.0.10:
https://jsfiddle.net/kaljak/5uudokuL/

Any idea when this will be released?

**Comment by larsac07** [comment]
Hi, @kaljak. We're [currently in alpha](http://www.highcharts.com/blog/news/highcharts-gantt-alpha/), and expecting beta sometime in Q2 :)
