### ISSUE TITLE
Legend navigation controls hidden and maxHeight ignored after calls to legend.update

### ISSUE THREAD

**Issue by jwickman** [highcharts/highcharts#6356]
#### Expected behaviour

In a chart with `legend:maxHeight` specified, after calling `legend.update()` the navigation controls should be displayed if legend height exceeds `maxHeight`.

#### Actual behaviour

The legend navigation dom nodes are gone after calling update multiple times, and/or `maxHeight` is ignored.

#### Live demo with steps to reproduce

**EXAMPLE 1:**
Small tweak to the legend.update example on api.highcharts.com, adding `maxHeight` in initial options: 
http://jsfiddle.net/mkz2mvpj/

Click the **Update Legend** button 3 times, and you will note that the navigation controls are gone.

**EXAMPLE 2:**
Slight tweak to example above, where I demonstrate that just calling `update()` multiple times is what messes this up (doesn't seem to be caused by whether navigation was necessary prior to the update call): 
http://jsfiddle.net/mkz2mvpj/1/

Click the **Update Legend** button twice, and you will note that the `maxHeight` is not applied and navigation controls are missing.

*NOTE*: I also tried adding `maxHeight` to the update options, which does not correct it.

#### Affected browser(s)

Found in Chrome 55, also found to affect FF 51 and IE 11.

**Comment by pawelfus** [comment]
Hi @jwickman 

Thank you for reporting. It's already reported here: #6322

And fixed in the master branch, take a look: http://jsfiddle.net/mkz2mvpj/2/

**Comment by jwickman** [comment]
@pawelfus Sorry for missing #6322 in my search, but that commit does not actually fix the 2nd case I submitted above.  See here:

http://jsfiddle.net/mkz2mvpj/3/

Upon second call to `update()` `maxHeight` is ignored, and navigation goes away.

**Comment by pawelfus** [comment]
Hi @jwickman 

My apologies for not paying full attention to the second case. Of course you are right,  let me reopen this ticket. Note: your second demo doesn't show navigation controls at all with Chrome+osx, but with decreased `maxHeight`, we can observe this issue: http://jsfiddle.net/mkz2mvpj/5/
