### ISSUE TITLE
Highstocks synchronized charts: Point highlighting out of sync

### ISSUE THREAD

**Issue by kolobix** [highcharts/highcharts#6595]
Hi,
it seems that the point highlighting is not working properly when synchronizing multiple charts with multiple series as you can see in this screenshot:
![highstocks_bug](https://cloud.githubusercontent.com/assets/22211305/25063079/a07d9c42-21da-11e7-8460-46355f0c6f3b.png)

Fiddle:
http://jsfiddle.net/ZArZM/316/
To reproduce the bug move your mouse a little from left to right and right to left above the first chart.

Expected behaviour:
All points of the current selection should be highlighted and synchronized while mouse moving (like the tooltips)

Actual behaviour:
Point highlighting is not synchronized or sometimes the points are not highlighted at all

**Comment by pawelfus** [comment]
Hi @kolobix 

Thank you for reporting the issue. It looks like a regression, it used to work in 5.0.7 fine.

*Internal note:*
Issue by commit leads to this commit: https://github.com/highcharts/highcharts/commit/e2afbd1

**Comment by jon-a-nygaard** [comment]
@kolobix You will have to explicitly set the state to normal, on points which no longer should have a hover state. [Here's an example of how to achieve this](http://jsfiddle.net/jon_a_nygaard/ZArZM/331/)

**Comment by AizeLeOuf** [comment]
@jon-a-nygaard Nice example but if we set 3 charts (more than 2), new bug (related?) appears and on the third chart only one serie is displayed :

http://jsfiddle.net/0muzu4t4/

![screenshot 2018-05-01 at 08 23 52](https://user-images.githubusercontent.com/8999614/39464108-e768def6-4d1b-11e8-8faf-f091d813d4ee.png)

**Comment by pawelfus** [comment]
@AizeLeOuf 

Thank you for the gifs. Interesting, it works fine for me on osx, but it's broken on windows machine.

**Comment by AizeLeOuf** [comment]
Any news ?

**Comment by jon-a-nygaard** [comment]
Hi @AizeLeOuf,

There seemed to be a small bug in the fiddle regarding the `points` passed into `tooltip.refresh`.
Here is an [updated example](http://jsfiddle.net/5xvtjm7k/) which should fix the issue.

Please let us know should there be anything else.

I will also close this issue as I consider it to be solved. Should this be incorrect then give us a comment and we will consider reopening the issue.

**Comment by AizeLeOuf** [comment]
Hi @jon-a-nygaard,

I'm still faced to strange issue about tooltips in synchronized chart here a new one from your example : 

http://jsfiddle.net/yvoezhpc/4/

Move your mouse on the first chart and lookup the third chart...

![image](https://user-images.githubusercontent.com/8999614/41097426-24ebd4d2-6a58-11e8-9654-df6e681b3910.png)
