### ISSUE TITLE
Chart doesn't fit parent on first draw

### ISSUE THREAD

**Issue by joris-** [highcharts/highcharts#7412]
Hi !
I'm using Highcharts with React and I get one issue with chart width.

#### Expected behaviour
I wish the chart fit the parent container on first draw.

#### Actual behaviour
On first draw my chart doesn't fit the parent container as you can see on the gif below. And on window resize or when I close a sidebar the chart get a normal width and fit the parent element.

#### Live demo with steps to reproduce

https://cl.ly/1c43300o1b38

```
import React, {Component} from 'react';
import PropTypes from 'prop-types';
import Highcharts from 'highcharts';

class HighchartsComponent extends Component {

    componentDidMount() {

        if (this.props.modules) {
            this.props.modules.forEach(module => {
                module(Highcharts);
            });
        }

        this.chart = Highcharts.chart(
            this.props.id,
            {
                chart: {
                    type: this.props.type
                },
                credits: {
                    enabled: false,
                },
                legend: {
                    enabled: false
                },
                series: [{
                    name: 'Browsers',
                    data: this.props.data,
                    size: '100%',
                    innerSize: '85%',
                    showInLegend:true,
                    dataLabels: {
                        enabled: true
                    }
                }],
                xAxis: {
                    visible: false
                },
                yAxis: {
                    visible: false
                },
            }
        );
    }

    //Destroy chart before unmount.
    componentWillUnmount() {
        this.chart.destroy();
    }

    render() {
        return <div id={this.props.id}></div>
    }
}

HighchartsComponent.propTypes = {
    id: PropTypes.string.isRequired,
    name: PropTypes.string,
    showInLegend: PropTypes.bool,
    dataLabels: PropTypes.shape({
        enabled: PropTypes.bool
    }),
    data: PropTypes.array.isRequired
};

export default HighchartsComponent;
```

#### Affected browser(s)
I'm getting problem on Safari, FF Quantum, Chrome (62) MacOs and on Linux also.

Thanks for your help :)

**Comment by pawelfus** [comment]
Hi @joris- 

Thank you for reporting this issue with all details. Could you recreate issue in the [sandbox](https://codesandbox.io/s/new)? I think this bug reminds me another one, but it should be fixed already - do you have v6.0.3?

**Comment by pawelfus** [comment]
Hi @joris- 

I'm not familiar with `ant.design`, so I'm not sure what causes the issue. I can only guess that `ant.design` creates a hidden container (`display:none;`) and browser returns `width: 0, height:0` so we can not calculate required dimensions for the SVG. Does `ant.design` provide a callback where you could call `chart.reflow()`?

**Comment by joris-** [comment]
@pawelfus 
I just try it but it doesn't works. I'm doing a `chart.reflow` on sidebar toggle and the chart still shown good when sidebar is closed whereas when sidebar is opened chart doesn't fit parent.

**Comment by joris-** [comment]
@pawelfus 
You can find an example here : https://codesandbox.io/s/4z5rrpq58w

**Comment by pawelfus** [comment]
Hi @joris- 

Thank you for the example. It looks like `chart.reflow()` resolves the issue. I'm not sure about `and.design`, but reflowing chart in the load callback by`setTimeout(fun, 0)` fixes the issue. Please take a look: https://codesandbox.io/s/r1o2r1pqjq

**Comment by joris-** [comment]
@pawelfus Thanks a lot, don't know if it's a good practice but do the job !
