### ISSUE TITLE
followTouchMove doesn't work properly on column series (mobile browser only)

### ISSUE THREAD

**Issue by kamilkulig** [highcharts/highcharts#7484]
#### Expected behaviour
Tooltip should always appear on the column under the pointer when `followTouchMove` is set to `true`.

#### Actual behavior
Sometimes tooltip remains in its previous position instead of following the drag movement (see the gif below).

![followtouchmove -test](https://user-images.githubusercontent.com/13188589/33557580-ef083392-d907-11e7-9c69-c44bcf367895.gif)

#### Live demo with steps to reproduce
Try to perform few drag moves like on the gif above.
http://jsfiddle.net/kkulig/njjuk9ke/

#### Reproduced on:
Chrome 62.0.3202.84
Android 6.0.1

**Comment by razmaimon** [comment]
More details here
https://stackoverflow.com/q/47494724/6578998

**Comment by TorsteinHonsi** [comment]
Steps to reproduce:

1. Open http://jsfiddle.net/highcharts/njjuk9ke/6/show in Chrome with mobile device emulation enabled.
2. Tag _on a column_ and drag.

**Comment by skuske** [comment]
@TorsteinHonsi 

Any timeframe when this will be fixed?

**Comment by skuske** [comment]
@TorsteinHonsi 

Any update, please!

**Comment by jon-a-nygaard** [comment]
This issue is fixed in pull request https://github.com/highcharts/highcharts/pull/8567, and will be included in an upcoming maintenance release.

**Comment by pawelfus** [comment]
OP demo is still broken: http://jsfiddle.net/kkulig/njjuk9ke/ - tooltip follows pointer, but it's not updated when hovering other column. @jon-a-nygaard

**Comment by skuske** [comment]
@pawelfus , @jon-a-nygaard 

When can we expect this to be fixed? We are waiting for months now, and the recent iOS wrapper which includes v6.1.2 actually made things even worse:

https://github.com/highcharts/highcharts-ios/issues/129

**Comment by TorsteinHonsi** [comment]
@skuske Thanks for your patience, we'll prioritize this.

A little recap for the buggy behaviour in v6.1.3. See http://jsfiddle.net/highcharts/njjuk9ke/16/.
1. When touching the white area (outside column, the tooltip follows touch move _and_ gets updated, even when touch-moving across columns.
2. When touching the columns, the tooltip contents get stuck with the touched column, and the touched column receives hover color, but the tooltip moves along with the touch.
3. Once we have touched a column, we cannot go back to situation 1. The next time we touch outside the columns, the closest column is highlighted and we're back to situation 2.

**Comment by TorsteinHonsi** [comment]
Demo with the fix applied: http://jsfiddle.net/highcharts/42m90Lso/show

**Comment by skuske** [comment]
@TorsteinHonsi 

Any chance that we can get the iOS warpper updated with that fix? Many thanks in advance!

**Comment by KacperMadej** [comment]
@skuske  The fix will be a part of the next code release, so it should be also available in corresponding wrapper for iOS release.

**Comment by skuske** [comment]
@KacperMadej 

OK, that means that we will have to wait another two months for the next iOS wrapper update?

**Comment by KacperMadej** [comment]
@skuske 

No, we do not have ETA for next release and iOS wrapper is usually updated up to few days after Highcharts release.

@TorsteinHonsi Do we have ETA for this fix to go live?

**Comment by TorsteinHonsi** [comment]
I realized this still doesn't work so it is supposed. I did another commit, see http://jsfiddle.net/highcharts/42m90Lso/show.

The default settings are that `followPointer` is false and `followTouchMove` is true. This means that the tooltip should be _updated_ as the finger moves across the plot area, but as the `followPointer` is false, it should point to the top of the columns, not stick to the finger.

@skuske I consider this a critical regression since all charts are buggy by default on all touch devices with the current version. Will immediately start the release process for a maintenance fix.

**Comment by skuske** [comment]
@TorsteinHonsi 

Thanks for the update. Looking forward to the final fix for that. :o)

**Comment by skuske** [comment]
@TorsteinHonsi 

Does 6.1.4 fix this?

**Comment by TorsteinHonsi** [comment]
Yes it does.

**Comment by skuske** [comment]
@TorsteinHonsi 

Cool. When will the iOS wrapper be updated accordingly?

**Comment by pawelfus** [comment]
@skuske  We will release iOS wrapper ASAP.

Answered: https://github.com/highcharts/highcharts-ios/issues/129#issuecomment-425015573
