### ISSUE TITLE
Weird horizontal lines show up after zoom-in on a boosted column chart

### ISSUE THREAD

**Issue by alirezameftahi71** [highcharts/highcharts#7716]
#### Scenario 
We have a column chart with totally 40000 data in 4 series. But  sometimes when we zoom in, we see a some random horizontal lines which are not supposed to be there.
See we zoom in the highlighted area of the chart like shown below:
![screenshot 294](https://user-images.githubusercontent.com/31916958/35283069-6bed5e10-006c-11e8-9a61-57c366992bc9.png)

#### Expected behaviour
What we expect is to zoom-in and not see any random horizontal lines on the chart.

#### Actual behaviour
But this is what we get:
![screenshot 295](https://user-images.githubusercontent.com/31916958/35282808-badf84f4-006b-11e8-9cbc-5654a30155d9.png)

#### Live demo
Check the jsfiddle link below:
https://jsfiddle.net/alinux7/qbd2vq0j/

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
Tested on:
Firefox, Chrome

**Comment by KacperMadej** [comment]
Hi @alirezameftahi71 

Thank you for reporting about the problem.

After second zoom the lines are not visible - at least for me after testing this.

_Internal note:_ not fixed in any ([1](https://github.com/highcharts/highcharts/tree/bugfix/7655-boost-wrong-marker-color), [2](https://github.com/highcharts/highcharts/tree/bugfix/7385-boost-arearange)) currently opened boost bugfix branches

**Comment by cvasseng** [comment]
A fix has been pushed for this, and is pending merging.

Preview of the fix: https://jsfiddle.net/vhLf5087/

**Comment by cvasseng** [comment]
Fixed in 6.0.5.

**Comment by alirezameftahi71** [comment]
Thank you @cvasseng . But there seems to be a problem. 
When I use the gitHub link in the jsFiddle, the issue IS fixed. But when I use the CDN, the lines still exist. 
I opened the CDN link and at the top it says it's the version 6.0.5.

**Comment by cvasseng** [comment]
We had an issue with preparing the release, resulting in this particular fix not making it into 6.0.5. 

There will be a maintenance release very soon that addresses this as well as a couple of regressions.
