### ISSUE TITLE
Line chart with boost showing points grouped into vertical lines instead of successively

### ISSUE THREAD

**Issue by andreassavva** [highcharts/highcharts#7744]
#### Expected behaviour
Line chart showing correctly.
![2](https://user-images.githubusercontent.com/11631813/35503209-c77f7764-04df-11e8-810f-26687f1969e9.PNG)

#### Actual behaviour
Line chart's points are shown grouped on vertical lines instead of successively next to each other, as they should. Enabling another serie and disabling it corrects it a lot of times, but temporarily.
![1](https://user-images.githubusercontent.com/11631813/35503219-cd1a20e8-04df-11e8-855d-071557def4a0.PNG)

#### Live demo with steps to reproduce
https://jsfiddle.net/andreassavva/6y1x83mv/
behavior is apparent as is, but try zooming in and clicking on other series to enable and disable them.

#### Product version
Highcharts 6.0.4

#### Affected browser(s)
Checked on Chrome and Firefox, assuming that other browsers also affected.

**Comment by pawelfus** [comment]
Hi @andreassavva 

Thank you for reporting the issue. Unfortunately, your demo doesn't work. Could you update the demo and let us know? Thanks!

**Comment by andreassavva** [comment]
You are right, it doesn't. I fixed it now, I think it works.

**Comment by pawelfus** [comment]
Unfortunately, still doesn't work: https://jsfiddle.net/andreassavva/6y1x83mv/ (even adding jQuery won't resolve the issues, AJAX paths are wrong).

![screen shot 2018-01-29 at 14 45 33](https://user-images.githubusercontent.com/1453926/35513378-1874a9b4-0503-11e8-882e-8911c45f7590.png)

**Comment by andreassavva** [comment]
Sorry, I updated the link now. Didn't know that JSfiddle changes the url by adding a number in the end every time you update.

**Comment by pawelfus** [comment]
Thank you @andreassavva - you are right, this looks wrong.

Simplified demo: https://jsfiddle.net/BlackLabel/6y1x83mv/10/ - @cvasseng could you take a look?

**Comment by cvasseng** [comment]
When using datetime axis with short intervals, GPU translations cannot be used, as floating point precision (or the lack of, rather) causes distorted translations.

So for these cases, 'useGPUTranslations` should either be left at its default value, or explicitly set to `false`.

With no GPU translations: https://jsfiddle.net/9rgbwjt8/
