### ISSUE TITLE
Reset zoom button does not appear when zooming (x or xy) stock chart 

### ISSUE THREAD

**Issue by kiren-aur** [highcharts/highcharts#8514]
#### Expected behaviour
When we zoom a stock chart, we expect a reset zoom button to appear.

#### Actual behaviour
When we zoom in a stock chart, with zoomType = 'x' or 'xy', the reset zoom button does not appear.
This weird behavior is only affecting stock charts and only these zoom types.
The documentation example shows this issue : https://api.highcharts.com/highstock/chart.zoomType
Check out 'x' and 'xy' links below (I took them directly from the doc.)
It seems that the same issue appeared in 2012, in this thread : https://github.com/highcharts/highcharts/issues/979 ; one of the proposed workaround is still a working solution. Here it is, for information :  

```
(function(H) {
     H.wrap(H.Axis.prototype, 'zoom', function(proceed, newMin, newMax) {
       var ret;

       this.chart.options.rangeSelector.enabled = false;
       this.chart.options.navigator.enabled = false;
       ret = proceed.call(this, newMin, newMax);
       this.chart.options.rangeSelector.enabled = true;
       this.chart.options.navigator.enabled = false;

       return ret;
     });
})(Highcharts);
```
#### Live demo with steps to reproduce
[zoomType : 'x'](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/chart/zoomtype-x/)
[zoomType : 'xy'](http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/stock/chart/zoomtype-xy/)
Steps : 
- Zoom in the charts
- "Try" to reset the zoom

#### Product version
Highstock JS v6.1.0 (2018-04-13)

#### Affected browser(s)
Chrome and Firefox

**Comment by pawelfus** [comment]
Hi @kiren-aur 

Thanks for reporting the issue. As described in #979 this should be fixed on our master branch, check this:

- `zoomType: 'xy'`: http://jsfiddle.net/BlackLabel/ue10zwc6/ (reset zoom button shows up)
- `zoomType: 'x'`: http://jsfiddle.net/BlackLabel/s59c7dbL/ (no reset zoom button)
- `zoomType: 'y'`: http://jsfiddle.net/BlackLabel/xsy6qej5/ (reset zoom button shows up)

**Comment by kiren-aur** [comment]
Hi Pawel, thank you very much for your answer!

**Comment by shunxing** [comment]
Hello @pawelfus

The problem still remains after zooming on the js fiddle above, the  reset zoom button does not appear 

<img width="743" alt="Image" src="https://github.com/user-attachments/assets/5fe600d9-557e-4936-8e46-2714db1621b0" />

**Comment by pawelfus** [comment]
Hi @shunxing - could you tell us which demo? There are three demos, and for two (`zoomType` = `y` or `xy`) it shows, and for `x` it doesn't (as expected, since the Navigator is enabled, there's no need to show the reset zoom button).
