### ISSUE TITLE
Boost mode boosts all curves if boostThreshold specified non-zero for more than 4 curves

### ISSUE THREAD

**Issue by rajeevsinghchib** [highcharts/highcharts#8919]
#### Expected behaviour
It should boost only the curves for which boostThreshold is specified greater than zero value

#### Actual behaviour
Its working as expected until we specify boostThreshold(>0) for less than 5 curves, but boosts all curves if boostThreshold specified for more than 5 curves.

#### Live demo with steps to reproduce
https://jsfiddle.net/Ldojf7r8/1/

#### Product version
Highstock JS v6.1.2

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
#### Workaround
Set `boost.allowForce` to false: http://jsfiddle.net/highcharts/yan68ku1/

**Comment by TorsteinHonsi** [comment]
It's expected behaviour as per the [boost.allowForce](https://api.highcharts.com/highcharts/boost.allowForce) option. Set it to false to disable: http://jsfiddle.net/highcharts/yan68ku1/.

**Comment by rajeevsinghchib** [comment]
This jsfiddle is not working and boost.allowForce is also not solving the problem.

Please look at the problem before closing the bug.

**Comment by rajeevsinghchib** [comment]
Please reopen this bug and close it when its fixed.

**Comment by pawelfus** [comment]
Fixed jsFiddle demo, please take a look: http://jsfiddle.net/BlackLabel/yan68ku1/1/

**Comment by rajeevsinghchib** [comment]
Not fixed, its fixed for 5, please take a look: http://jsfiddle.net/yan68ku1/6/

**Comment by TorsteinHonsi** [comment]
Thanks, I see the difference now! So even when `boost.allowForce` is false, it forces boost if there are more than 5 boosted series.

**Comment by cvasseng** [comment]
I've added an issue for this here: https://github.com/highcharts/highcharts/issues/8950

**Comment by rajeevsinghchib** [comment]
Many Thanks!
