### ISSUE TITLE
Chart with shared tooltip and boost module crashes when updating data and tooltip

### ISSUE THREAD

**Issue by ppotaczek** [highcharts/highcharts#9572]
#### Expected behaviour

http://jsfiddle.net/BlackLabel/8jearmuz/

#### Actual behaviour

`Uncaught TypeError: Cannot read property 'series' of undefined`

#### Live demo with steps to reproduce
http://jsfiddle.net/BlackLabel/vh4sjxt6/

1. Hover on series
2. Check for update

#### Product version
Highcharts 6.2.0

#### Affected browser(s)
All

**Comment by TorsteinHonsi** [comment]
It seems it is already fixed: http://jsfiddle.net/1dmby4pk/

**Comment by jonfreedman** [comment]
@TorsteinHonsi this started from [this issue here](https://github.com/highcharts/highcharts-react/issues/74), can you explain how to modify https://codesandbox.io/s/zlozmoy1l4 to resolve the issue?

**Comment by pawelfus** [comment]
Hi @jonfreedman 

Does `codesandbox.io` support loading dependancies from github? Issues is resolved on our `master` branch so either use that version (not recommended) or wait until v7 will be released (this month).

**Comment by jonfreedman** [comment]
@pawelfus thanks for clarifying, as I suspected `s/already fixed/will be fixed in the next release/`

**Comment by ppotaczek** [comment]
It looks like this bug is not solved. There is still a problem with updating multiple series:

http://jsfiddle.net/BlackLabel/5nc34j1g/

**Comment by KacperMadej** [comment]
@cvasseng fyi: boost issue
