### ISSUE TITLE
Highcharts.dateFormats is readonly

### ISSUE THREAD

**Issue by gmiller-in-situ** [highcharts/highcharts#9920]
#### Expected behaviour
I expect to be able to set custom date formatters through Highcharts.dateFormats like so:
`Highcharts.dateFormats = {
    Q: function(timestamp) {
        return timestamp + '';
    },
};`

#### Actual behaviour
Highcharts.dateFormats is readonly in the typescript module, and so an error is raised by my IDE when I try to assign this value.

#### Live demo with steps to reproduce
I don't see the typescript module on the CDN, so not sure I can reproduce in a fiddle.

#### Product version
Highcharts 7.0.1

#### Affected browser(s)
I'm working with Jetbrains Webstorm

**Comment by KacperMadej** [comment]
Hi @gmiller-in-situ 

Thank you for reporting about the problem.

Please copy and share the error message (might be censored if it contains confidential info, but we need something).

I'm unable to recreate the problem. As long as you will define new function with correct type it runs fine for me. Tested on Sublime with TypeScript package.

![ts-error](https://user-images.githubusercontent.com/8960408/51278271-73ed3080-19da-11e9-9603-bbffe6c3e365.jpg)

Bonus info: if you want to check the `.d.ts` files without loading via NPM use `highcharts-dist` repo, e.g.: https://raw.githubusercontent.com/highcharts/highcharts-dist/master/highcharts.src.d.ts

**Comment by gmiller-in-situ** [comment]
I see where I went wrong with this now: I was having trouble assigning the function like so: `Highcharts.dateFormats = { Q: QFunc };` because for some reason the `highcharts.dateFormats` property is `undefined` when I'm trying to do this assignment. 
As a workaround, I was assigning `Highcharts.dateFormats` to a new object, which typescript warns about because I am reassigning a readonly `let`.

Assigning as `Highcharts.dateFormats.Q = QFunc;` has no typescript warning, but the `Highcharts.dateFormats` property is still `undefined` at runtime, so this is causing problems.

**Comment by KacperMadej** [comment]
Right, `Highcharts.dateFormats` is undefined by default. ( In pure JS demo the object is initialized at first - http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/global/dateformats/ ).

_Internal note:_
@bre1470 
Is there an easy fix in TS type definitions for `Highcharts.dateFormats` to prevent this error?
Alternatively we could define `Highcharts.dateFormats` as an empty object in core to avoid this problem.

**Comment by KacperMadej** [comment]
As reported by @Timppe (https://github.com/highcharts/highcharts/pull/9951#issuecomment-458863202) the property is still a read-only property, so the problem is with assigning a new object to the property.

As I mentioned before, we could define `Highcharts.dateFormats` as an empty object in core to avoid this problem.

**Comment by TorsteinHonsi** [comment]
I would prefer a solution that doesn't change the actual JS implementation.

**Comment by bre1470** [comment]
It has been solved (in the master for now) by initializing it with an empty object, so that it can be used as a dictionary.

**Comment by SaeedZhiany** [comment]
@TorsteinHonsi and @KacperMadej 
The issue is not resolved yet, I'm getting the typescript error too.
(I'm using V7.1.2)

![image](https://user-images.githubusercontent.com/13766432/64169364-e83dec80-ce62-11e9-9f28-80f166786151.png)

**Comment by bre1470** [comment]
@SaeedZhiany It is a constant, use it like a dictionary. See the example: http://jsfiddle.net/gh/get/library/pure/highcharts/highcharts/tree/master/samples/highcharts/global/dateformats/
