### ISSUE TITLE
Get SVG after running highcharts on Node.

### ISSUE THREAD

**Issue by souravsingh-blr** [highcharts/highcharts#9968]
#### Expected behaviour
I am using Node to run my javascript code. I am using jsdom to create dom and divContainer.
After attaching the highcharts specific input to the div. I am trying to get the SVG.
SVG after running on Node is not correct. I compared this SVG with svg generated in normal browser with fiddle, and there were differences between the two svg.

```
var fs = require('fs');
let jsdom = require('jsdom').JSDOM;
html = ''+
'<!DOCTYPE html>'+
    '<html>'+
    '<head>'+
        '<title>Blank</title>'+
    '</head>'+
    '<body>'+
        '<p>Hello World</p>'+
    '<div id="container" style="width:864px;height:800px">dfdf</div></body>'+
'</html>';
 
// get the dom by calling the jsdom constructor, and giving it the html
dom = new jsdom(html);
 
// get the window object @ dom.window
window = dom.window;
var Highcharts=require('highcharts');
require('highcharts/modules/exporting')(Highcharts);
// some hard coded html


// now just do whatever, just like in the browser
el = window.document.querySelectorAll('p')[0];
div= window.document.querySelectorAll('div')[0];
/* console.log(el.innerHTML); 
console.log(div.innerHTML);
console.log(div.style.width);
console.log(div.style.height); */
var x=Highcharts.chart('container',  {

  title: {
      text: 'Solar Employment Growth by Sector, 2010-2016'
  },

  subtitle: {
      text: 'Source: thesolarfoundation.com'
  },

  yAxis: {
      title: {
          text: 'Number of Employees'
      }
  },
  legend: {
      layout: 'vertical',
      align: 'right',
      verticalAlign: 'middle'
  },

  plotOptions: {
      series: {
          label: {
              connectorAllowed: false
          },
          pointStart: 2010
      }
  },
  //forExport: true,
  series: [{
      name: 'Installation',
      data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
  }, {
      name: 'Manufacturing',
      data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
  }, {
      name: 'Sales & Distribution',
      data: [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]
  }, {
      name: 'Project Development',
      data: [null, null, 7988, 12169, 15112, 22452, 34400, 34227]
  }, {
      name: 'Other',
      data: [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]
  }],

  

});
console.log(x.getSVG()); 
fs.writeFile('chart.svg', x.getSVG(), function () {
  console.log('Wrote ' + x.getSVG().length + ' bytes to ' +  'chart.svg.'); // eslint-disable-line no-path-concat
});
```

#### Actual behaviour
I need the same SVG as if I am running on the normal browser which renders correctly and which might be converted to an image.

#### Product version

Highcharts Latest
#### Affected browser(s)
Node

**Comment by TorsteinHonsi** [comment]
Hi,
We have an npm package for this purpose. See https://www.npmjs.com/package/highcharts-jsdom.

**Comment by souravsingh-blr** [comment]
What should be inside input file "examples/bubble.json"?
I tried putting below code and it was giving error.undefined:2
    title: {
    ^

SyntaxError: Unexpected token t in JSON at position 7
`{
    title: {
        text: 'Solar Employment Growth by Sector, 2010-2016'
    },

    subtitle: {
        text: 'Source: thesolarfoundation.com'
    },

    yAxis: {
        title: {
            text: 'Number of Employees'
        }
    },
    legend: {
        layout: 'vertical',
        align: 'right',
        verticalAlign: 'middle'
    },

    plotOptions: {
        series: {
            label: {
                connectorAllowed: false
            },
            pointStart: 2010
        }
    },

    series: [{
        name: 'Installation',
        data: [43934, 52503, 57177, 69658, 97031, 119931, 137133, 154175]
    }, {
        name: 'Manufacturing',
        data: [24916, 24064, 29742, 29851, 32490, 30282, 38121, 40434]
    }, {
        name: 'Sales & Distribution',
        data: [11744, 17722, 16005, 19771, 20185, 24377, 32147, 39387]
    }, {
        name: 'Project Development',
        data: [null, null, 7988, 12169, 15112, 22452, 34400, 34227]
    }, {
        name: 'Other',
        data: [12908, 5948, 8105, 11248, 8989, 11816, 18274, 18111]
    }],

    responsive: {
        rules: [{
            condition: {
                maxWidth: 500
            },
            chartOptions: {
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                }
            }
        }]
    }

}`

test.js file:
`const hc = require('highcharts-jsdom');
 
hc({
    infile: 'test.json',
    outfile: 'chart.svg',
 
    // Constructor, defaults to 'chart'
    constr: 'chart',
 
    // Module files etc
    extensions: [
        'highcharts-more'
    ]
}).then((result) => {
    console.log(result);
});`

**Comment by souravsingh-blr** [comment]
> Hi,
> We have an npm package for this purpose. See https://www.npmjs.com/package/highcharts-jsdom.

Thanks for the answer. I need something in which I can have the SVG directly. Here input is a file and output is a file. I need the input and output in some variable instead of file. Please help this is needed urgently.

**Comment by TorsteinHonsi** [comment]
Please use https://www.npmjs.com/package/highcharts-export-server. It is faster and produces better looking charts than the JSDOM approach.

**Comment by KacperMadej** [comment]
Looks like the issue is resolved, so it will now be closed.
If you would like to see this issues reopened, please leave a comment with new and relevant info.

**Comment by BrentGrammer** [comment]
This is still an issue for us.  We would like to get the SVG from the chart in memory.  Currently we have to generate a temp file and read that to get the SVG as a string using highcharts-export-server.  Is there a way to avoid having to generate the file and access the SVG in memory?  We are not able to call .getSVG() on the chart rendering our component server-side.

**Comment by pawelfus** [comment]
Hi @BrentGrammer 

Could you please contact our support and provide more details? See: https://www.highcharts.com/blog/support/ - it's hard to guess why you are not able to call `getSVG()` on your server-side component.

**Comment by BrentGrammer** [comment]
> Hi @BrentGrammer
> 
> Could you please contact our support and provide more details? See: https://www.highcharts.com/blog/support/ - it's hard to guess why you are not able to call `getSVG()` on your server-side component.

Ok, I'll contact support.  Basically, we need to get the SVG string from the chart server side to send it in a response to a call to our endpoint.  When we call chart.getSVG(), an error is thrown, '_highcharts.default.Chart is not a constructor'.  Maybe it's because we don't have a DOM?  Needless to say, we're stuck on this since we would like to just get the SVG in memory and not have to make a temp svg file to extract the SVG string.
